#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NONE 0
#define HEAL_LOCATION_WAKABA_TOWN_PLAYERS_HOUSE_2F 1
#define HEAL_LOCATION_YOSHINO_CITY 2
#define HEAL_LOCATION_KIKYOU_CITY 3
#define HEAL_LOCATION_HIWADA_TOWN 4
#define HEAL_LOCATION_KOGANE_CITY 5
#define HEAL_LOCATION_ENJU_CITY 6
#define HEAL_LOCATION_ASAGI_CITY 7
#define HEAL_LOCATION_TANBA_CITY 8
#define HEAL_LOCATION_CHOUJI_TOWN 9
#define HEAL_LOCATION_FUSUBE_CITY 10
#define HEAL_LOCATION_INDIGO_PLATEAU 11
#define HEAL_LOCATION_SILVER_CAVE 12
#define HEAL_LOCATION_BATTLE_FRONTIER 13
#define HEAL_LOCATION_ROUTE_32 14
#define HEAL_LOCATION_COUNT 15

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
