#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_NONE 0
#define HEAL_LOCATION_WAKABA_TOWN_PLAYERS_HOUSE_2F 1
#define HEAL_LOCATION_YOSHINO_CITY 2
#define HEAL_LOCATION_KIKYOU_CITY 3
#define HEAL_LOCATION_HIWADA_TOWN 4
#define HEAL_LOCATION_KOGANE_CITY 5
#define HEAL_LOCATION_ENJU_CITY 6
#define HEAL_LOCATION_ASAGI_CITY 7
#define HEAL_LOCATION_TANBA_CITY 8
#define HEAL_LOCATION_CHOUJI_TOWN 9
#define HEAL_LOCATION_FUSUBE_CITY 10
#define HEAL_LOCATION_JITTERBUG_TOWN 11
#define HEAL_LOCATION_INDIGO_PLATEAU 12
#define HEAL_LOCATION_SILVER_CAVE 13
#define HEAL_LOCATION_BATTLE_FRONTIER 14
#define HEAL_LOCATION_ROUTE_32 15
#define HEAL_LOCATION_MASARA_TOWN 16
#define HEAL_LOCATION_TOKIWA_CITY 17
#define HEAL_LOCATION_NIBI_CITY 18
#define HEAL_LOCATION_HANADA_CITY 19
#define HEAL_LOCATION_KUCHIBA_CITY 20
#define HEAL_LOCATION_CION_TOWN 21
#define HEAL_LOCATION_TAMAMUSHI_CITY 22
#define HEAL_LOCATION_SEKICHIKU_CITY 23
#define HEAL_LOCATION_YAMABUKI_CITY 24
#define HEAL_LOCATION_GUREN_TOWN 25
#define HEAL_LOCATION_COUNT 26

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
