#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_NONE                         0
#define MAPSEC_WAKABA_TOWN                  1
#define MAPSEC_KIKYOU_CITY                  2
#define MAPSEC_HIWADA_TOWN                  3
#define MAPSEC_KOGANE_CITY                  4
#define MAPSEC_ENJU_CITY                    5
#define MAPSEC_ASAGI_CITY                   6
#define MAPSEC_TANBA_CITY                   7
#define MAPSEC_CHOUJI_TOWN                  8
#define MAPSEC_FUSUBE_CITY                  9
#define MAPSEC_ROUTE_23                     10
#define MAPSEC_ROUTE_26                     11
#define MAPSEC_ROUTE_27                     12
#define MAPSEC_ROUTE_28                     13
#define MAPSEC_ROUTE_29                     14
#define MAPSEC_ROUTE_30                     15
#define MAPSEC_ROUTE_31                     16
#define MAPSEC_ROUTE_32                     17
#define MAPSEC_ROUTE_33                     18
#define MAPSEC_ROUTE_34                     19
#define MAPSEC_ROUTE_35                     20
#define MAPSEC_ROUTE_36                     21
#define MAPSEC_ROUTE_37                     22
#define MAPSEC_ROUTE_38                     23
#define MAPSEC_ROUTE_39                     24
#define MAPSEC_ROUTE_40                     25
#define MAPSEC_ROUTE_41                     26
#define MAPSEC_ROUTE_42                     27
#define MAPSEC_ROUTE_43                     28
#define MAPSEC_ROUTE_44                     29
#define MAPSEC_ROUTE_45                     30
#define MAPSEC_ROUTE_46                     31
#define MAPSEC_ROUTE_47                     32
#define MAPSEC_ROUTE_48                     33
#define MAPSEC_ROUTE_32_POKECENTER          34
#define MAPSEC_SILVER_CAVE_POKECENTER       35   
#define MAPSEC_DARK_CAVE                    36
#define MAPSEC_UNION_CAVE                   37
#define MAPSEC_SPROUT_TOWER                 38  
#define MAPSEC_SLOWPOKE_WELL                39
#define MAPSEC_ILEX_FOREST                  40
#define MAPSEC_RADIO_TOWER                  41
#define MAPSEC_NATIONAL_PARK                42
#define MAPSEC_RUINS_OF_ALPH                43
#define MAPSEC_SINJOH_RUINS                 44
#define MAPSEC_BRASS_TOWER                  45
#define MAPSEC_TIN_TOWER                    46
#define MAPSEC_BATTLE_FRONTIER              47
#define MAPSEC_SEASIDE_CAVE                 48
#define MAPSEC_SECRET_GARDEN                49
#define MAPSEC_LIGHTHOUSE                   50
#define MAPSEC_WHIRL_ISLANDS                51
#define MAPSEC_MT_MORTAR                    52
#define MAPSEC_LAKE_OF_RAGE                 53
#define MAPSEC_ICE_PATH                     54
#define MAPSEC_DRAGONS_DEN                  55
#define MAPSEC_TOHJO_FALLS                  56
#define MAPSEC_VICTORY_ROAD                 57
#define MAPSEC_INDIGO_PLATEAU               58
#define MAPSEC_SILVER_CAVE                  59
#define MAPSEC_MT_SILVER                    60
#define MAPSEC_EMBEDDED_TOWER               61     
#define MAPSEC_SAFARI_ZONE                  62

#define MAPSEC_MASARA_TOWN                  63
#define MAPSEC_TOKIWA_CITY                  64
#define MAPSEC_NIBI_CITY                    65
#define MAPSEC_HANADA_CITY                  66
#define MAPSEC_CION_TOWN                    67
#define MAPSEC_KUCHIBA_CITY                 68
#define MAPSEC_TAMAMUSHI_CITY               69
#define MAPSEC_SEKICHIKU_CITY               70
#define MAPSEC_CERULEAN_ISLAND              71   
#define MAPSEC_YAMABUKI_CITY                72
#define MAPSEC_ROUTE_1                      73
#define MAPSEC_ROUTE_2                      74
#define MAPSEC_ROUTE_3                      75
#define MAPSEC_ROUTE_4                      76
#define MAPSEC_ROUTE_5                      77
#define MAPSEC_ROUTE_6                      78
#define MAPSEC_ROUTE_7                      79
#define MAPSEC_ROUTE_8                      80
#define MAPSEC_ROUTE_9                      81
#define MAPSEC_ROUTE_10                     82
#define MAPSEC_ROUTE_11                     83
#define MAPSEC_ROUTE_12                     84
#define MAPSEC_ROUTE_13                     85
#define MAPSEC_ROUTE_14                     86
#define MAPSEC_ROUTE_15                     87
#define MAPSEC_ROUTE_16                     88
#define MAPSEC_ROUTE_17                     89
#define MAPSEC_ROUTE_18                     90
#define MAPSEC_ROUTE_19                     91
#define MAPSEC_ROUTE_20                     92
#define MAPSEC_ROUTE_21                     93
#define MAPSEC_ROUTE_22                     94
#define MAPSEC_ROUTE_23_KANTO               95
#define MAPSEC_ROUTE_24                     96
#define MAPSEC_ROUTE_25                     97
#define MAPSEC_ROUTE_4_POKECENTER           98
#define MAPSEC_ROUTE_10_POKECENTER          99
#define MAPSEC_VIRIDIAN_FOREST              100
#define MAPSEC_MT_MOON                      101
#define MAPSEC_S_S_ANNE                     102
#define MAPSEC_UNDERGROUND_PATH             103
#define MAPSEC_UNDERGROUND_PATH_2           104
#define MAPSEC_DIGLETTS_CAVE                105
#define MAPSEC_ROCKET_HIDEOUT               106
#define MAPSEC_SILPH_CO                     107
#define MAPSEC_POKEMON_MANSION              108
#define MAPSEC_KANTO_SAFARI_ZONE            109
#define MAPSEC_ROCK_TUNNEL                  110
#define MAPSEC_SEAFOAM_ISLANDS              111
#define MAPSEC_POKEMON_TOWER                112
#define MAPSEC_CERULEAN_CAVE                113
#define MAPSEC_POWER_PLANT                  114

#define MAPSECS_SEVII_123                   115

#define MAPSEC_ONE_ISLAND                   116
#define MAPSEC_TWO_ISLAND                   117
#define MAPSEC_THREE_ISLAND                 118
#define MAPSEC_FOUR_ISLAND                  119
#define MAPSEC_FIVE_ISLAND                  120
#define MAPSEC_SEVEN_ISLAND                 121
#define MAPSEC_SIX_ISLAND                   122
#define MAPSEC_KINDLE_ROAD                  123
#define MAPSEC_TREASURE_BEACH               124
#define MAPSEC_CAPE_BRINK                   125
#define MAPSEC_BOND_BRIDGE                  126
#define MAPSEC_THREE_ISLE_PORT              127
#define MAPSEC_SEVII_ISLE_6                 128
#define MAPSEC_SEVII_ISLE_7                 129
#define MAPSEC_SEVII_ISLE_8                 130
#define MAPSEC_SEVII_ISLE_9                 131
#define MAPSEC_RESORT_GORGEOUS              132
#define MAPSEC_WATER_LABYRINTH              133
#define MAPSEC_FIVE_ISLE_MEADOW             134
#define MAPSEC_MEMORIAL_PILLAR              135
#define MAPSEC_OUTCAST_ISLAND               136
#define MAPSEC_GREEN_PATH                   137
#define MAPSEC_WATER_PATH                   138
#define MAPSEC_RUIN_VALLEY                  139
#define MAPSEC_TRAINER_TOWER                140
#define MAPSEC_CANYON_ENTRANCE              141
#define MAPSEC_SEVAULT_CANYON               142
#define MAPSEC_TANOBY_RUINS                 143
#define MAPSEC_SEVII_ISLE_22                144
#define MAPSEC_SEVII_ISLE_23                145
#define MAPSEC_SEVII_ISLE_24                146
#define MAPSEC_NAVEL_ROCK                   147
#define MAPSEC_MT_EMBER                     148
#define MAPSEC_BERRY_FOREST                 149
#define MAPSEC_ICEFALL_CAVE                 150
#define MAPSEC_ROCKET_WAREHOUSE             151
#define MAPSEC_TRAINER_TOWER_2              152
#define MAPSEC_DOTTED_HOLE                  153
#define MAPSEC_LOST_CAVE                    154
#define MAPSEC_PATTERN_BUSH                 155
#define MAPSEC_ALTERING_CAVE                156
#define MAPSEC_TANOBY_CHAMBERS              157
#define MAPSEC_THREE_ISLE_PATH              158
#define MAPSEC_TANOBY_KEY                   159
#define MAPSEC_BIRTH_ISLAND                 160
#define MAPSEC_MONEAN_CHAMBER               161
#define MAPSEC_LIPTOO_CHAMBER               162
#define MAPSEC_WEEPTH_CHAMBER               163
#define MAPSEC_DILFORD_CHAMBER              164
#define MAPSEC_SCUFIB_CHAMBER               165
#define MAPSEC_RIXY_CHAMBER                 166
#define MAPSEC_VIAPOIS_CHAMBER              167
#define MAPSEC_EMBER_SPA                    168
#define MAPSEC_SPECIAL_AREA                 169

#define MAPSEC_SECRET_BASE                  251
#define MAPSEC_DYNAMIC                      252

#define METLOC_SPECIAL_EGG                  253
#define METLOC_IN_GAME_TRADE                254
#define METLOC_FATEFUL_ENCOUNTER            255

#define KANTO_MAPSEC_START  MAPSEC_MASARA_TOWN
#define KANTO_MAPSEC_END    MAPSEC_SPECIAL_AREA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#define MAPSEC_LITTLEROOT_TOWN              170
#define MAPSEC_OLDALE_TOWN                  171
#define MAPSEC_DEWFORD_TOWN                 172
#define MAPSEC_LAVARIDGE_TOWN               173
#define MAPSEC_FALLARBOR_TOWN               174
#define MAPSEC_VERDANTURF_TOWN              175
#define MAPSEC_PACIFIDLOG_TOWN              176
#define MAPSEC_PETALBURG_CITY               177
#define MAPSEC_SLATEPORT_CITY               178
#define MAPSEC_MAUVILLE_CITY                179
#define MAPSEC_RUSTBORO_CITY                180
#define MAPSEC_FORTREE_CITY                 181
#define MAPSEC_LILYCOVE_CITY                182
#define MAPSEC_MOSSDEEP_CITY                183
#define MAPSEC_SOOTOPOLIS_CITY              184
#define MAPSEC_EVER_GRANDE_CITY             185
#define MAPSEC_ROUTE_101                    186
#define MAPSEC_ROUTE_102                    187
#define MAPSEC_ROUTE_103                    188
#define MAPSEC_ROUTE_104                    189
#define MAPSEC_ROUTE_105                    190
#define MAPSEC_ROUTE_106                    191
#define MAPSEC_ROUTE_107                    192
#define MAPSEC_ROUTE_108                    193
#define MAPSEC_ROUTE_109                    194
#define MAPSEC_ROUTE_110                    195
#define MAPSEC_ROUTE_111                    196
#define MAPSEC_ROUTE_112                    197
#define MAPSEC_ROUTE_113                    198
#define MAPSEC_ROUTE_114                    199
#define MAPSEC_ROUTE_115                    200
#define MAPSEC_ROUTE_116                    201
#define MAPSEC_ROUTE_117                    202
#define MAPSEC_ROUTE_118                    203
#define MAPSEC_ROUTE_119                    204
#define MAPSEC_ROUTE_120                    205
#define MAPSEC_ROUTE_121                    206
#define MAPSEC_ROUTE_122                    207
#define MAPSEC_ROUTE_123                    208
#define MAPSEC_ROUTE_124                    209
#define MAPSEC_ROUTE_125                    210
#define MAPSEC_ROUTE_126                    211
#define MAPSEC_ROUTE_127                    212
#define MAPSEC_ROUTE_128                    213
#define MAPSEC_ROUTE_129                    214
#define MAPSEC_ROUTE_130                    215
#define MAPSEC_ROUTE_131                    216
#define MAPSEC_ROUTE_132                    217
#define MAPSEC_ROUTE_133                    218
#define MAPSEC_ROUTE_134                    219
#define MAPSEC_UNDERWATER_124               MAPSEC_NONE
#define MAPSEC_UNDERWATER_126               MAPSEC_NONE
#define MAPSEC_UNDERWATER_127               MAPSEC_NONE
#define MAPSEC_UNDERWATER_128               MAPSEC_NONE
#define MAPSEC_UNDERWATER_SOOTOPOLIS        MAPSEC_NONE
#define MAPSEC_GRANITE_CAVE                 MAPSEC_NONE
#define MAPSEC_MT_CHIMNEY                   MAPSEC_NONE
#define MAPSEC_PETALBURG_WOODS              MAPSEC_NONE
#define MAPSEC_RUSTURF_TUNNEL               MAPSEC_NONE
#define MAPSEC_ABANDONED_SHIP               MAPSEC_NONE
#define MAPSEC_NEW_MAUVILLE                 MAPSEC_NONE
#define MAPSEC_METEOR_FALLS                 MAPSEC_NONE
#define MAPSEC_METEOR_FALLS2                MAPSEC_NONE
#define MAPSEC_MT_PYRE                      MAPSEC_NONE
#define MAPSEC_AQUA_HIDEOUT_OLD             MAPSEC_NONE
#define MAPSEC_SHOAL_CAVE                   MAPSEC_NONE
#define MAPSEC_SEAFLOOR_CAVERN              MAPSEC_NONE
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   MAPSEC_NONE
#define MAPSEC_MIRAGE_ISLAND                MAPSEC_NONE
#define MAPSEC_CAVE_OF_ORIGIN               MAPSEC_NONE
#define MAPSEC_SOUTHERN_ISLAND              MAPSEC_NONE
#define MAPSEC_FIERY_PATH                   MAPSEC_NONE
#define MAPSEC_FIERY_PATH2                  MAPSEC_NONE
#define MAPSEC_JAGGED_PASS                  MAPSEC_NONE
#define MAPSEC_JAGGED_PASS2                 MAPSEC_NONE
#define MAPSEC_SEALED_CHAMBER               MAPSEC_NONE
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    MAPSEC_NONE
#define MAPSEC_SCORCHED_SLAB                MAPSEC_NONE
#define MAPSEC_ISLAND_CAVE                  MAPSEC_NONE
#define MAPSEC_DESERT_RUINS                 MAPSEC_NONE
#define MAPSEC_ANCIENT_TOMB                 MAPSEC_NONE
#define MAPSEC_INSIDE_OF_TRUCK              MAPSEC_NONE
#define MAPSEC_SKY_PILLAR                   MAPSEC_NONE
#define MAPSEC_NAVEL_ROCK_FRLG              MAPSEC_NONE
#define MAPSEC_ALTERING_CAVE_FRLG           MAPSEC_NONE
#define MAPSEC_BIRTH_ISLAND_FRLG            MAPSEC_NONE
#define MAPSEC_AQUA_HIDEOUT                 MAPSEC_NONE
#define MAPSEC_MAGMA_HIDEOUT                MAPSEC_NONE
#define MAPSEC_MIRAGE_TOWER                 MAPSEC_NONE
#define MAPSEC_FARAWAY_ISLAND               MAPSEC_NONE
#define MAPSEC_ARTISAN_CAVE                 MAPSEC_NONE
#define MAPSEC_MARINE_CAVE                  MAPSEC_NONE
#define MAPSEC_UNDERWATER_MARINE_CAVE       MAPSEC_NONE
#define MAPSEC_TERRA_CAVE                   MAPSEC_NONE
#define MAPSEC_UNDERWATER_105               MAPSEC_NONE
#define MAPSEC_UNDERWATER_125               MAPSEC_NONE
#define MAPSEC_UNDERWATER_129               MAPSEC_NONE
#define MAPSEC_DESERT_UNDERPASS             MAPSEC_NONE
#define MAPSEC_TRAINER_HILL                 MAPSEC_NONE

#endif //GUARD_REGIONMAPSEC_H272
