#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_LITTLEROOT_TOWN              0x00
#define MAPSEC_OLDALE_TOWN                  0x01
#define MAPSEC_DEWFORD_TOWN                 0x02
#define MAPSEC_LAVARIDGE_TOWN               0x03
#define MAPSEC_FALLARBOR_TOWN               0x04
#define MAPSEC_VERDANTURF_TOWN              0x05
#define MAPSEC_PACIFIDLOG_TOWN              0x06
#define MAPSEC_PETALBURG_CITY               0x07
#define MAPSEC_SLATEPORT_CITY               0x08
#define MAPSEC_MAUVILLE_CITY                0x09
#define MAPSEC_RUSTBORO_CITY                0x0A
#define MAPSEC_FORTREE_CITY                 0x0B
#define MAPSEC_LILYCOVE_CITY                0x0C
#define MAPSEC_MOSSDEEP_CITY                0x0D
#define MAPSEC_SOOTOPOLIS_CITY              0x0E
#define MAPSEC_EVER_GRANDE_CITY             0x0F
#define MAPSEC_ROUTE_101                    0x10
#define MAPSEC_ROUTE_102                    0x11
#define MAPSEC_ROUTE_103                    0x12
#define MAPSEC_ROUTE_104                    0x13
#define MAPSEC_ROUTE_105                    0x14
#define MAPSEC_ROUTE_106                    0x15
#define MAPSEC_ROUTE_107                    0x16
#define MAPSEC_ROUTE_108                    0x17
#define MAPSEC_ROUTE_109                    0x18
#define MAPSEC_ROUTE_110                    0x19
#define MAPSEC_ROUTE_111                    0x1A
#define MAPSEC_ROUTE_112                    0x1B
#define MAPSEC_ROUTE_113                    0x1C
#define MAPSEC_ROUTE_114                    0x1D
#define MAPSEC_ROUTE_115                    0x1E
#define MAPSEC_ROUTE_116                    0x1F
#define MAPSEC_ROUTE_117                    0x20
#define MAPSEC_ROUTE_118                    0x21
#define MAPSEC_ROUTE_119                    0x22
#define MAPSEC_ROUTE_120                    0x23
#define MAPSEC_ROUTE_121                    0x24
#define MAPSEC_ROUTE_122                    0x25
#define MAPSEC_ROUTE_123                    0x26
#define MAPSEC_ROUTE_124                    0x27
#define MAPSEC_ROUTE_125                    0x28
#define MAPSEC_ROUTE_126                    0x29
#define MAPSEC_ROUTE_127                    0x2A
#define MAPSEC_ROUTE_128                    0x2B
#define MAPSEC_ROUTE_129                    0x2C
#define MAPSEC_ROUTE_130                    0x2D
#define MAPSEC_ROUTE_131                    0x2E
#define MAPSEC_ROUTE_132                    0x2F
#define MAPSEC_ROUTE_133                    0x30
#define MAPSEC_ROUTE_134                    0x31
#define MAPSEC_UNDERWATER_124               0x32
#define MAPSEC_UNDERWATER_126               0x33
#define MAPSEC_UNDERWATER_127               0x34
#define MAPSEC_UNDERWATER_128               0x35
#define MAPSEC_UNDERWATER_SOOTOPOLIS        0x36
#define MAPSEC_GRANITE_CAVE                 0x37
#define MAPSEC_MT_CHIMNEY                   0x38
#define MAPSEC_SAFARI_ZONE                  0x39
#define MAPSEC_BATTLE_FRONTIER              0x3A
#define MAPSEC_PETALBURG_WOODS              0x3B
#define MAPSEC_RUSTURF_TUNNEL               0x3C
#define MAPSEC_ABANDONED_SHIP               0x3D
#define MAPSEC_NEW_MAUVILLE                 0x3E
#define MAPSEC_METEOR_FALLS                 0x3F
#define MAPSEC_METEOR_FALLS2                0x40
#define MAPSEC_MT_PYRE                      0x41
#define MAPSEC_AQUA_HIDEOUT_OLD             0x42
#define MAPSEC_SHOAL_CAVE                   0x43
#define MAPSEC_SEAFLOOR_CAVERN              0x44
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN   0x45
#define MAPSEC_VICTORY_ROAD                 0x46
#define MAPSEC_MIRAGE_ISLAND                0x47
#define MAPSEC_CAVE_OF_ORIGIN               0x48
#define MAPSEC_SOUTHERN_ISLAND              0x49
#define MAPSEC_FIERY_PATH                   0x4A
#define MAPSEC_FIERY_PATH2                  0x4B
#define MAPSEC_JAGGED_PASS                  0x4C
#define MAPSEC_JAGGED_PASS2                 0x4D
#define MAPSEC_SEALED_CHAMBER               0x4E
#define MAPSEC_UNDERWATER_SEALED_CHAMBER    0x4F
#define MAPSEC_SCORCHED_SLAB                0x50
#define MAPSEC_ISLAND_CAVE                  0x51
#define MAPSEC_DESERT_RUINS                 0x52
#define MAPSEC_ANCIENT_TOMB                 0x53
#define MAPSEC_INSIDE_OF_TRUCK              0x54
#define MAPSEC_SKY_PILLAR                   0x55
#define MAPSEC_SECRET_BASE                  0x56
#define MAPSEC_DYNAMIC                      0x57
#define MAPSEC_MASARA_TOWN                  88
#define MAPSEC_TOKIWA_CITY                  89
#define MAPSEC_NIBI_CITY                    90
#define MAPSEC_HANADA_CITY                  91
#define MAPSEC_CION_TOWN                    92
#define MAPSEC_KUCHIBA_CITY                 93
#define MAPSEC_TAMAMUSHI_CITY               94
#define MAPSEC_SEKICHIKU_CITY               95
#define MAPSEC_YAMABUKI_CITY                96
#define MAPSEC_GUREN_TOWN                   97 
#define MAPSEC_ROUTE_1                      98
#define MAPSEC_ROUTE_2                      99
#define MAPSEC_ROUTE_3                      100
#define MAPSEC_ROUTE_4                      101
#define MAPSEC_ROUTE_5                      102
#define MAPSEC_ROUTE_6                      103
#define MAPSEC_ROUTE_7                      104
#define MAPSEC_ROUTE_8                      105
#define MAPSEC_ROUTE_9                      106
#define MAPSEC_ROUTE_10                     107
#define MAPSEC_ROUTE_11                     108
#define MAPSEC_ROUTE_12                     109
#define MAPSEC_ROUTE_13                     110
#define MAPSEC_ROUTE_14                     111
#define MAPSEC_ROUTE_15                     112
#define MAPSEC_ROUTE_16                     113
#define MAPSEC_ROUTE_17                     114
#define MAPSEC_ROUTE_18                     115
#define MAPSEC_ROUTE_19                     116
#define MAPSEC_ROUTE_20                     117
#define MAPSEC_ROUTE_21                     118
#define MAPSEC_ROUTE_22                     119
#define MAPSEC_ROUTE_23_KANTO               120
#define MAPSEC_ROUTE_24                     121
#define MAPSEC_ROUTE_25                     122
#define MAPSEC_ROUTE_4_POKECENTER           123
#define MAPSEC_ROUTE_10_POKECENTER          124
#define MAPSEC_VIRIDIAN_FOREST              125
#define MAPSEC_MT_MOON                      126
#define MAPSEC_S_S_ANNE                     127
#define MAPSEC_UNDERGROUND_PATH             128
#define MAPSEC_UNDERGROUND_PATH_2           129
#define MAPSEC_DIGLETTS_CAVE                130
#define MAPSEC_ROCKET_HIDEOUT               131
#define MAPSEC_SILPH_CO                     132
#define MAPSEC_POKEMON_MANSION              133
#define MAPSEC_KANTO_SAFARI_ZONE            134
#define MAPSEC_ROCK_TUNNEL                  135
#define MAPSEC_SEAFOAM_ISLANDS              136
#define MAPSEC_POKEMON_TOWER                137
#define MAPSEC_CERULEAN_CAVE                138
#define MAPSEC_POWER_PLANT                  139
#define MAPSECS_SEVII_123                   140
#define MAPSEC_ONE_ISLAND                   141
#define MAPSEC_TWO_ISLAND                   142
#define MAPSEC_THREE_ISLAND                 143
#define MAPSEC_FOUR_ISLAND                  144
#define MAPSEC_FIVE_ISLAND                  145
#define MAPSEC_SEVEN_ISLAND                 146
#define MAPSEC_SIX_ISLAND                   147
#define MAPSEC_KINDLE_ROAD                  148
#define MAPSEC_TREASURE_BEACH               149
#define MAPSEC_CAPE_BRINK                   150
#define MAPSEC_BOND_BRIDGE                  151
#define MAPSEC_THREE_ISLE_PORT              152
#define MAPSEC_SEVII_ISLE_6                 153
#define MAPSEC_SEVII_ISLE_7                 154
#define MAPSEC_SEVII_ISLE_8                 155
#define MAPSEC_SEVII_ISLE_9                 156
#define MAPSEC_RESORT_GORGEOUS              157
#define MAPSEC_WATER_LABYRINTH              158
#define MAPSEC_FIVE_ISLE_MEADOW             159
#define MAPSEC_MEMORIAL_PILLAR              160
#define MAPSEC_OUTCAST_ISLAND               161
#define MAPSEC_GREEN_PATH                   162
#define MAPSEC_WATER_PATH                   163
#define MAPSEC_RUIN_VALLEY                  164
#define MAPSEC_TRAINER_TOWER                165
#define MAPSEC_CANYON_ENTRANCE              166
#define MAPSEC_SEVAULT_CANYON               167
#define MAPSEC_TANOBY_RUINS                 168
#define MAPSEC_SEVII_ISLE_22                169
#define MAPSEC_SEVII_ISLE_23                170
#define MAPSEC_SEVII_ISLE_24                171
#define MAPSEC_NAVEL_ROCK                   172
#define MAPSEC_MT_EMBER                     173
#define MAPSEC_BERRY_FOREST                 174
#define MAPSEC_ICEFALL_CAVE                 175
#define MAPSEC_ROCKET_WAREHOUSE             176
#define MAPSEC_TRAINER_TOWER_2              177
#define MAPSEC_DOTTED_HOLE                  178
#define MAPSEC_LOST_CAVE                    179
#define MAPSEC_PATTERN_BUSH                 180
#define MAPSEC_ALTERING_CAVE                181
#define MAPSEC_TANOBY_CHAMBERS              182
#define MAPSEC_THREE_ISLE_PATH              183
#define MAPSEC_TANOBY_KEY                   184
#define MAPSEC_BIRTH_ISLAND                 185
#define MAPSEC_MONEAN_CHAMBER               186
#define MAPSEC_LIPTOO_CHAMBER               187
#define MAPSEC_WEEPTH_CHAMBER               188
#define MAPSEC_DILFORD_CHAMBER              189
#define MAPSEC_SCUFIB_CHAMBER               190
#define MAPSEC_RIXY_CHAMBER                 191
#define MAPSEC_VIAPOIS_CHAMBER              192
#define MAPSEC_EMBER_SPA                    193
#define MAPSEC_WAKABA_TOWN                  194
#define MAPSEC_YOSHINO_CITY                 195
#define MAPSEC_KIKYOU_CITY                  196
#define MAPSEC_HIWADA_TOWN                  197
#define MAPSEC_KOGANE_CITY                  198
#define MAPSEC_ENJU_CITY                    199
#define MAPSEC_ASAGI_CITY                   200
#define MAPSEC_TANBA_CITY                   201
#define MAPSEC_CHOUJI_TOWN                  202
#define MAPSEC_FUSUBE_CITY                  203
#define MAPSEC_ROUTE_23                     204
#define MAPSEC_ROUTE_26                     205
#define MAPSEC_ROUTE_27                     206
#define MAPSEC_ROUTE_28                     207
#define MAPSEC_ROUTE_29                     208
#define MAPSEC_ROUTE_30                     209
#define MAPSEC_ROUTE_31                     210
#define MAPSEC_ROUTE_32                     211
#define MAPSEC_ROUTE_33                     212
#define MAPSEC_ROUTE_34                     213
#define MAPSEC_ROUTE_35                     214
#define MAPSEC_ROUTE_36                     215
#define MAPSEC_ROUTE_37                     216
#define MAPSEC_ROUTE_38                     217
#define MAPSEC_ROUTE_39                     218
#define MAPSEC_ROUTE_40                     219
#define MAPSEC_ROUTE_41                     220
#define MAPSEC_ROUTE_42                     221
#define MAPSEC_ROUTE_43                     222
#define MAPSEC_ROUTE_44                     223
#define MAPSEC_ROUTE_45                     224
#define MAPSEC_ROUTE_46                     225
#define MAPSEC_ROUTE_47                     226
#define MAPSEC_ROUTE_48                     227
#define MAPSEC_ROUTE_32_BONEKACENTER        228
#define MAPSEC_SILVER_CAVE_BONEKACENTER     229   
#define MAPSEC_DARK_CAVE                    230
#define MAPSEC_UNION_CAVE                   231
#define MAPSEC_SPROUT_TOWER                 232  
#define MAPSEC_SLOWPOKE_WELL                233
#define MAPSEC_ILEX_FOREST                  234
#define MAPSEC_RADIO_TOWER                  235
#define MAPSEC_NATIONAL_PARK                236
#define MAPSEC_RUINS_OF_ALPH                237
#define MAPSEC_SINJOH_RUINS                 238
#define MAPSEC_BRASS_TOWER                  239
#define MAPSEC_TIN_TOWER                    240
#define MAPSEC_SEASIDE_CAVE                 241
#define MAPSEC_SECRET_GARDEN                242
#define MAPSEC_LIGHTHOUSE                   243
#define MAPSEC_WHIRL_ISLANDS                244
#define MAPSEC_MT_MORTAR                    245
#define MAPSEC_LAKE_OF_RAGE                 246
#define MAPSEC_ICE_PATH                     247
#define MAPSEC_SNOWTOP_MOUNTAIN             248
#define MAPSEC_DRAGONS_DEN                  249
#define MAPSEC_TOHJO_FALLS                  250
#define MAPSEC_INDIGO_PLATEAU               251
#define MAPSEC_SILVER_CAVE                  252
#define MAPSEC_MT_SILVER                    253
#define MAPSEC_EMBEDDED_TOWER               254     
#define MAPSEC_NONE                         255

#define METLOC_SPECIAL_EGG                  253
#define METLOC_IN_GAME_TRADE                254
#define METLOC_FATEFUL_ENCOUNTER            255

#define KANTO_MAPSEC_START  MAPSEC_MASARA_TOWN
#define KANTO_MAPSEC_END    MAPSEC_EMBER_SPA
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H
