 gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Oak_Welcome::
	.string "Sorry to keep you waiting!\p"
	.string "Welcome to the world of Bonéka!\p"
	.string "My name is Professor Oak.\p"
	.string "But everyone calls me the Bonéka\n"
	.string "Professor.\p"
	.string "Before we go any further, i'd like\n"
	.string "to tell you a few things you should\l"
	.string "know about this world!\p"
	.string "$"


gText_ThisIsABoneka::
	.string "This world is widely inhabitated\n"
	.string "by creatures known as Bonéka.\p"
	.string "$"

gText_Oak_MainSpeech::
	.string "We humans live alongside Bonéka\n"
	.string "as friends.\p"
	.string "At times we play together, and at\n"
	.string "other times we work together.\p"
	.string "Some people use their Bonéka to\n"
	.string "battle and develop closer bonds\l"
	.string "with them./p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Now, why dont you tell me a little bit\n"
	.string "about yourself?\p"
	.string "$"

gText_Oak_BoyOrGirl::
	.string "Are you boyish?\n"
	.string "Or are you a girly?\p"
	.string "Why won't you please tell me?\p"
	.string "$"

gText_Oak_WhatsYourName::
	.string "Please tell me your name.\p$"

gText_Oak_SoItsPlayer::
	.string "Your name is {PLAYER}{KUN}?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}{KUN}!\p$"

gText_Oak_AreYouReady::
	.string "Are you ready?\n"
	.string "Your very own tale of grand adventure\l"
	.string "is about to unfold.\p"
	.string "Fun experiences, difficult experiences,\n"
	.string "there's so much waiting for you!\l"
	.string "Dreams! Adventure!\p"
	.string "Let's go to the world of Bonéka.\p"
	.string "I'll see you later!\p"
	.string "$"



