gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the Bonéka Center.\p"
	.string "We restore your tired Bonéka\n"
	.string "to full health.\p"
	.string "Would you like to rest your Bonéka?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your Bonéka\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your Bonéka\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the Bonéka Center.\p"
	.string "We restore your tired Bonéka\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The Gold Card?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several Puppeteers with\n"
	.string "a Silver Card before, but, {PLAYER},\l"
	.string "you're the first Puppeteer I've ever\l"
	.string "seen with a Gold Card!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your Bonéka!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your Bonéka\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"
