#include "global.h"
#include "strings.h"
#include "battle_pyramid_bag.h"
#include "item_menu.h"

ALIGNED(4)
const u8 gText_ExpandedPlaceholder_Empty[] = _("");
const u8 gText_ExpandedPlaceholder_Kun[] = _("");
const u8 gText_ExpandedPlaceholder_Chan[] = _("");
const u8 gText_ExpandedPlaceholder_Sapphire[] = _("Sapphire");
const u8 gText_ExpandedPlaceholder_Ruby[] = _("Ruby");
const u8 gText_ExpandedPlaceholder_Emerald[] = _("Emerald");
const u8 gText_ExpandedPlaceholder_Aqua[] = _("Aqua");
const u8 gText_ExpandedPlaceholder_Magma[] = _("Magma");
const u8 gText_ExpandedPlaceholder_Archie[] = _("Archie");
const u8 gText_ExpandedPlaceholder_Maxie[] = _("Maxie");
const u8 gText_ExpandedPlaceholder_Kyogre[] = _("Kyogre");
const u8 gText_ExpandedPlaceholder_Groudon[] = _("Groudon");
const u8 gText_ExpandedPlaceholder_Brendan[] = _("Brendan");
const u8 gText_ExpandedPlaceholder_May[] = _("May");
const u8 gText_EggNickname[] = _("Egg");
const u8 gText_Pokemon[] = _("Bonéka");
const u8 gText_Player[] = _("Player"); // Unused
const u8 gText_Pokedex[] = _("Artbook"); // Unused
const u8 gText_Time[] = _("Time");
const u8 gText_Badges[] = _("Badges"); // Unused
const u8 gText_AButton[] = _("A Button"); // Unused
const u8 gText_BButton[] = _("B Button"); // Unused
const u8 gText_RButton[] = _("R Button"); // Unused
const u8 gText_LButton[] = _("L Button"); // Unused
const u8 gText_Start[] = _("Start"); // Unused
const u8 gText_Select[] = _("Select"); // Unused
const u8 gText_ControlPad[] = _("+ Control Pad"); // Unused
const u8 gText_LButtonRButton[] = _("L Button  R Button"); // Unused
const u8 gText_Controls[] = _("Controls"); // Unused
ALIGNED(4) const u8 gText_PickOk[] = _("{DPAD_UPDOWN}Pick {A_BUTTON}OK"); // Unused
ALIGNED(4) const u8 gText_Next[] = _("{A_BUTTON}Next"); // Unused
ALIGNED(4) const u8 gText_NextBack[] = _("{A_BUTTON}Next {B_BUTTON}Back"); // Unused
ALIGNED(4) const u8 gText_PickNextCancel[] = _("{DPAD_UPDOWN}Pick {A_BUTTON}Next {B_BUTTON}Cancel");
ALIGNED(4) const u8 gText_PickCancel[] = _("{DPAD_UPDOWN}Pick {A_BUTTON}{B_BUTTON}Cancel");
ALIGNED(4) const u8 gText_AButtonExit[] = _("{A_BUTTON}Exit");
const u8 gText_ThisIsAPokemon[] = _("This is what we call a “Bonéka.”{PAUSE 96}\p");
const u8 gText_5MarksPokemon[] = _("????? Bonéka");
const u8 gText_UnkHeight[] = _("{CLEAR_TO 0x0C}??'??”");
const u8 gText_UnkHeightMetric[] = _("???.? m");
const u8 gText_UnkWeight[] = _("????.? lbs.");
const u8 gText_UnkWeightMetric[] = _("???.? kg.");
const u8 gText_EmptyPkmnCategory[] = _("                       Bonéka"); // Unused
const u8 gText_EmptyHeight[] = _("{CLEAR_TO 0x0C}    '    ”"); // Unused
const u8 gText_EmptyWeight[] = _("        .   lbs."); // Unused
const u8 gText_EmptyPokedexInfo1[] = _(""); // Unused
const u8 gText_CryOf[] = _("CRY OF");
const u8 gText_EmptyPokedexInfo2[] = _(""); // Unused
const u8 gText_SizeComparedTo[] = _("Size compared to ");
const u8 gText_PokedexRegistration[] = _("Artbook registration completed.");
const u8 gText_HTHeight[] = _("HT");
const u8 gText_WTWeight[] = _("WT");
const u8 gText_SearchingPleaseWait[] = _("Searching…\nPlease wait.");
const u8 gText_SearchCompleted[] = _("Search completed.");
const u8 gText_NoMatchingPkmnWereFound[] = _("No matching Bonéka were found.");
const u8 gText_SearchForPkmnBasedOnParameters[] = _("Search for Bonéka based on\nselected parameters.");
const u8 gText_SwitchPokedexListings[] = _("Switch Artbook listings.");
const u8 gText_ReturnToPokedex[] = _("Return to the Artbook.");
const u8 gText_SelectPokedexMode[] = _("Select the Artbook mode.");
const u8 gText_SelectPokedexListingMode[] = _("Select the Artbook listing mode.");
const u8 gText_ListByFirstLetter[] = _("List by the first letter in the name.\nSpotted Bonéka only.");
const u8 gText_ListBySourceGame[] = _("List by source game.\nSpotted Bonéka only.");
const u8 gText_ListByType[] = _("List by type.\nOwned Bonéka only.");
const u8 gText_ExecuteSearchSwitch[] = _("Execute search/switch.");
const u8 gText_DexHoennTitle[] = _("Hoenn Artbook");
const u8 gText_DexNatTitle[] = _("National Artbook");
const u8 gText_DexSortNumericalTitle[] = _("Numerical Mode");
const u8 gText_DexSortAtoZTitle[] = _("A to Z Mode");
const u8 gText_DexSortHeaviestTitle[] = _("Heaviest Mode");
const u8 gText_DexSortLightestTitle[] = _("Lightest Mode");
const u8 gText_DexSortTallestTitle[] = _("Tallest Mode");
const u8 gText_DexSortSmallestTitle[] = _("Smallest Mode");
const u8 gText_DexSearchAlphaABC[] = _("ABC");
const u8 gText_DexSearchAlphaDEF[] = _("DEF");
const u8 gText_DexSearchAlphaGHI[] = _("GHI");
const u8 gText_DexSearchAlphaJKL[] = _("JKL");
const u8 gText_DexSearchAlphaMNO[] = _("MNO");
const u8 gText_DexSearchAlphaPQR[] = _("PQR");
const u8 gText_DexSearchAlphaSTU[] = _("STU");
const u8 gText_DexSearchAlphaVWX[] = _("VWX");
const u8 gText_DexSearchAlphaYZ[] = _("YZ");
const u8 gText_DexSearchSourceHRTP[]     = _("HRtP");
const u8 gText_DexSearchSourceSOEW[]     = _("SoEW");
const u8 gText_DexSearchSourcePODD[]     = _("PoDD");
const u8 gText_DexSearchSourceLLS[]      = _("LLS");
const u8 gText_DexSearchSourceMS[]       = _("MS");
const u8 gText_DexSearchSourceEOSD[]     = _("EoSD");
const u8 gText_DexSearchSourcePCB[]      = _("PCB");
const u8 gText_DexSearchSourceIN[]       = _("IN");
const u8 gText_DexSearchSourcePOFV[]     = _("PoFV");
const u8 gText_DexSearchSourceMOF[]      = _("MoF");
const u8 gText_DexSearchSourceSA[]       = _("SA");
const u8 gText_DexSearchSourceUFO[]      = _("UFO");
const u8 gText_DexSearchSourceTD[]       = _("TD");
const u8 gText_DexSearchSourceDDC[]      = _("DDC");
const u8 gText_DexSearchSourceLOLK[]     = _("LoLK");
const u8 gText_DexSearchSourceHSIFS[]    = _("HSiFS");
const u8 gText_DexSearchSourceWBAWC[]    = _("WBaWC");
const u8 gText_DexSearchSourceUM[]       = _("UM");
const u8 gText_DexSearchSourceUDOALG[]   = _("UDoALG");
const u8 gText_DexSearchSourceFW[]       = _("FW");
const u8 gText_DexSearchSourceSPINOFF[]  = _("Spinoffs");
const u8 gText_DexSearchSourcePRINT[]    = _("Print Works");
const u8 gText_DexSearchSourceOTHER[]    = _("Other");
const u8 gText_DexHRTPDescription[]      = _("01: Reiiden (Wondrous Tale) {EMOJI_TILDE}\nThe Highly Responsive to Prayers. (1996)");
const u8 gText_DexSOEWDescription[]      = _("02: Fumaroku (Demon-Sealing Record) {EMOJI_TILDE}\nthe Story of Eastern Wonderland. (1997)");
const u8 gText_DexPODDDescription[]      = _("03: Yumejikuu (Space Time Dream) {EMOJI_TILDE}\nthe Phantasmagoria of Dim.Dream. (1997)");
const u8 gText_DexLLSDescription[]       = _("04: Gensoukyou (Fantasy Land) {EMOJI_TILDE}\nLotus Land Story. (1998)");
const u8 gText_DexMSDescription[]        = _("05: Kaikidan (Bizarre Romantic Story) {EMOJI_TILDE}\nMystic Square. (1999)");
const u8 gText_DexEOSDDescription[]      = _("06: Koumakyou (Scarlet Devil Land) {EMOJI_TILDE}\nthe Embodiment of Scarlet Devil. (2002)");
const u8 gText_DexPCBDescription[]       = _("07: Youyoumu (Ghostly Dream) {EMOJI_TILDE}\nPerfect Cherry Blossom. (2003)");
const u8 gText_DexINDescription[]        = _("08: Eiyashou (Eternal Night Vignette) {EMOJI_TILDE}\nImperishable Night. (2004)");
const u8 gText_DexPOFVDescription[]      = _("09: Kaeizuka (Flower Reflecting Mound) {EMOJI_TILDE}\nPhantasmagoria of Flower View. (2005)");
const u8 gText_DexMOFDescription[]       = _("10: Fuujinroku (Wind God Chronicles) {EMOJI_TILDE}\nMountain of Faith. (2007)");
const u8 gText_DexSADescription[]        = _("11: Chireiden (Earth Spirit Palace) {EMOJI_TILDE}\nSubterranean Animism. (2008)");
const u8 gText_DexUFODescription[]       = _("12: Seirensen (Star Lotus Ship) {EMOJI_TILDE}\nUndefined Fantastic Object. (2009)");
const u8 gText_DexTDDescription[]        = _("13: Shinreibyou (Divine Spirit Mausoleum) {EMOJI_TILDE}\nTen Desires. (2011)");
const u8 gText_DexDDCDescription[]       = _("14: Kishinjou (Shining Needle Castle) {EMOJI_TILDE}\nDouble Dealing Character. (2013)");
const u8 gText_DexLOLKDescription[]      = _("15: Kanjuden (Ultramarine Orb Tale) {EMOJI_TILDE}\nLegacy of Lunatic Kingdom. (2015)");
const u8 gText_DexHSIFSDescription[]     = _("16: Tenkuushou (Heavenly Jade Dipper) {EMOJI_TILDE}\nHidden Star in Four Seasons. (2017)");
const u8 gText_DexWBAWCDescription[]     = _("17: Kikeijuu (Oni-Shaped Beast) {EMOJI_TILDE}\nWily Beast and Weakest Creature. (2019)");
const u8 gText_DexUMDescription[]        = _("18: Kouryuudou (Rainbow Dragon Cave) {EMOJI_TILDE}\nUnconnected Marketeers. (2021)");
const u8 gText_DexUDOALGDescription[]    = _("19: Juuouen (Beast King Garden) {EMOJI_TILDE}\nUnfinished Dream of All Living Ghost. (2023)");
const u8 gText_DexFWDescription[]        = _("20: Kinjoukyou (Crowning Glory Capital) {EMOJI_TILDE}\nFossilized Wonders. (2025)");
const u8 gText_DexSpinoffDescription[]   = _("Characters originating from non-mainline\nentries, such as fighting games.");
const u8 gText_DexPrintWDescription[]    = _("Characters originating from comics,\nmagazines, and music albums.");
const u8 gText_DexOtherDescription[]     = _("Characters from fan works,\ninternet memes, or other universes.");
const u8 gText_DexHoennDescription[] = _("Hoenn region's Artbook");
const u8 gText_DexNatDescription[] = _("National edition Artbook");
const u8 gText_DexSortNumericalDescription[] = _("Bonéka are listed according to their\nnumber.");
const u8 gText_DexSortAtoZDescription[] = _("Spotted and owned Bonéka are listed\nalphabetically.");
const u8 gText_DexSortHeaviestDescription[] = _("Owned Bonéka are listed from the\nheaviest to the lightest.");
const u8 gText_DexSortLightestDescription[] = _("Owned Bonéka are listed from the\nlightest to the heaviest.");
const u8 gText_DexSortTallestDescription[] = _("Owned Bonéka are listed from the\ntallest to the smallest.");
const u8 gText_DexSortSmallestDescription[] = _("Owned Bonéka are listed from the\nsmallest to the tallest.");
const u8 gText_DexEmptyString[] = _("");
const u8 gText_DexSearchDontSpecify[] = _("Don't specify.");
const u8 gText_DexSearchTypeNone[] = _("None");
const u8 gText_SelectorArrow[] = _("▶");
const u8 gText_EmptySpace[] = _(" "); // Unused
const u8 gText_WelcomeToHOF[] = _("Welcome to the Hall of Fame!");
const u8 gText_HOFDexRating[] = _("Spotted Bonéka: {STR_VAR_1}!\nOwned Bonéka: {STR_VAR_2}!\pProf. Birch's Artbook rating!\pProf. Birch: Let's see…\p");
const u8 gText_HOFDexSaving[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u8 gText_HOFCorrupted[] = _("The HalL of Fame data is corrupted.");
const u8 gText_HOFNumber[] = _("Hall of Fame No. {STR_VAR_1}");
const u8 gText_LeagueChamp[] = _("League Champion!\nCongratulations!");
const u8 gText_Number[] = _("No. ");
const u8 gText_Level[] = _("Lv. ");
const u8 gText_IdNumberSlash[] = _("IDNo. /"); // Unused
const u8 gText_Name[] = _("Name");
const u8 gText_IDNumber[] = _("IDNo.");
const u8 gText_BirchInTrouble[] = _("Prof. Birch is in trouble!\nRelease a Bonéka and rescue him!");
const u8 gText_ConfirmStarterChoice[] = _("Do you choose this Bonéka?");
const u8 gText_Pokemon4[] = _("Bonéka"); // Unused
const u8 gText_FlyToWhere[] = _("Fly to where?");
const u8 gMenuText_Use[] = _("Use");
const u8 gMenuText_Toss[] = _("Toss");
const u8 gMenuText_Register[] = _("Register");
const u8 gMenuText_Give[] = _("Give");
const u8 gMenuText_Confirm[] = _("Confirm");
const u8 gText_Cancel[] = _("Cancel");
const u8 gText_Cancel2[] = _("Cancel");
const u8 gText_EmptyString2[] = _("");
const u8 gText_None[] = _("None");
const u8 gText_FiveMarks[] = _("?????");
const u8 gText_Slash[] = _("/");
const u8 gText_OneDash[] = _("-");
const u8 gText_TwoDashes[] = _("--");
const u8 gText_ThreeDashes[] = _("---");
const u8 gText_MaleSymbol[] = _("♂");
const u8 gText_FemaleSymbol[] = _("♀");
const u8 gText_LevelSymbol[] = _("{LV}");
const u8 gText_NumberClear01[] = _("{NO}{CLEAR 0x01}");
const u8 gText_RightArrow[] = _("{RIGHT_ARROW}"); // Unused
const u8 gText_IDNumber2[] = _("{ID}{NO}");
const u8 gText_Space[] = _(" ");
const u8 gText_SelectorArrow2[] = _("▶");
const u8 gText_GoBackPrevMenu[] = _("Go back to the\nprevious menu.");
const u8 gText_WhatWouldYouLike[] = _("What would you like to do?");
const u8 gMenuText_Give2[] = _("Give");
const u8 gText_xVar1[] = _("×{STR_VAR_1}");
const u8 gText_Berry2[] = _(" Berry"); // Unused
const u8 gText_Coins[] = _("{STR_VAR_1} Coins");
const u8 gText_CloseBag[] = _("Close Bag");
const u8 gText_Var1IsSelected[] = _("{STR_VAR_1}\nis selected.");
const u8 gText_CantWriteMail[] = _("You can't write\nMAIL here.");
const u8 gText_NoPokemon[] = _("There is no\nBonéka.");
const u8 gText_MoveVar1Where[] = _("Move the\n{STR_VAR_1}\nwhere?");
const u8 gText_Var1CantBeHeld[] = _("The {STR_VAR_1} can't be held.");
const u8 gText_TossHowManyVar1s[] = _("Toss out how many\n{STR_VAR_1}?");
const u8 gText_ThrewAwayVar2Var1s[] = _("Threw away {STR_VAR_2}\n{STR_VAR_1}.");
const u8 gText_ConfirmTossItems[] = _("Is it okay to\nthrow away {STR_VAR_2}\n{STR_VAR_1}?");
const u8 gText_DadsAdvice[] = _("Dad's advice…\n{PLAYER}, there's a time and place for\leverything!{PAUSE_UNTIL_PRESS}");
const u8 gText_PlayerUsedVar2[] = _("{PLAYER} used the\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_RepelEffectsLingered[] = _("But the effects of a RepeL\nlingered from earlier.{PAUSE_UNTIL_PRESS}");
const u8 gText_LureEffectsLingered[] = _("But the effects of a Lure\nlingered from earlier.{PAUSE_UNTIL_PRESS}");
const u8 gText_BoxFull[] = _("The Box is full.{PAUSE_UNTIL_PRESS}");
const u8 gText_TheField[] = _("the field");
const u8 gText_TheBattle[] = _("the battle");
const u8 gText_ThePokemonList[] = _("the Bonéka List");
const u8 gText_TheShop[] = _("the shop");
const u8 gText_ThePC[] = _("the PC");

const u8 *const gBagMenu_ReturnToStrings[] =
{
    [ITEMMENULOCATION_FIELD]               = gText_TheField,
    [ITEMMENULOCATION_BATTLE]              = gText_TheBattle,
    [ITEMMENULOCATION_PARTY]               = gText_ThePokemonList,
    [ITEMMENULOCATION_SHOP]                = gText_TheShop,
    [ITEMMENULOCATION_BERRY_TREE]          = gText_TheField,
    [ITEMMENULOCATION_BERRY_BLENDER_CRUSH] = gText_TheField,
    [ITEMMENULOCATION_ITEMPC]              = gText_ThePC,
    [ITEMMENULOCATION_FAVOR_LADY]          = gText_TheField,
    [ITEMMENULOCATION_QUIZ_LADY]           = gText_TheField,
    [ITEMMENULOCATION_APPRENTICE]          = gText_TheField,
    [ITEMMENULOCATION_WALLY]               = gText_TheBattle,
    [ITEMMENULOCATION_PCBOX]               = gText_ThePC,
    [ITEMMENULOCATION_BERRY_TREE_MULCH]    = gText_TheField,
};

const u8 *const gPyramidBagMenu_ReturnToStrings[] =
{
    [PYRAMIDBAG_LOC_FIELD]       = gText_TheField,
    [PYRAMIDBAG_LOC_BATTLE]      = gText_TheBattle,
    [PYRAMIDBAG_LOC_PARTY]       = gText_ThePokemonList,
    [PYRAMIDBAG_LOC_CHOOSE_TOSS] = gText_TheField
};

const u8 gText_ReturnToVar1[] = _("Return to\n{STR_VAR_1}.");

const u8 *const gPocketNamesStringsTable[] =
{
    [ITEMS_POCKET] =    COMPOUND_STRING("Items"),
    [BALLS_POCKET] =    COMPOUND_STRING("Sealing Orbs"),
    [TMHM_POCKET]  =    COMPOUND_STRING("TMs & HMs"),
    [BERRIES_POCKET] =  COMPOUND_STRING("Berries"),
    [KEYITEMS_POCKET] = COMPOUND_STRING("Key Items")
};

const u8 gText_NumberItem_TMBerry[] = _("{NO}{STR_VAR_1}{CLEAR 0x07}{STR_VAR_2}");
const u8 gText_NumberItem_HM[] = _("{CLEAR_TO 0x11}{STR_VAR_1}{CLEAR 0x05}{STR_VAR_2}");

const u8 gText_ShopBuy[] = _("Buy");
const u8 gText_ShopSell[] = _("Sell");
const u8 gText_ShopQuit[] = _("Quit");
const u8 gText_ThatItemIsSoldOut[] = _("I'm sorry, but that item is sold out.{PAUSE_UNTIL_PRESS}");
const u8 gText_SoldOut[] = _("Sold Out");
const u8 gText_InBagVar1[] = _("In Bag: {STR_VAR_1}");
const u8 gText_QuitShopping[] = _("Quit shopping.");
const u8 gText_Var1CertainlyHowMany[] = _("{STR_VAR_1}? Certainly.\nHow many would you like?");
const u8 gText_Var1CertainlyHowMany2[] = _("{STR_VAR_1}? Certainly.\nHow many would you like?");
const u8 gText_Var1AndYouWantedVar2[] = _("{STR_VAR_1}? And you wanted {STR_VAR_2}?\nThat will be ¥{STR_VAR_3}.");
const u8 gText_Var1IsItThatllBeVar2[] = _("{STR_VAR_1}, is it?\nThat'll be ¥{STR_VAR_2}. Do you want it?");
const u8 gText_YouWantedVar1ThatllBeVar2[] = _("You wanted {STR_VAR_1}?\nThat'll be ¥{STR_VAR_2}. Will that be okay?");
const u8 gText_HereYouGoThankYou[] = _("Here you go!\nThank you very much.");
const u8 gText_ThankYouIllSendItHome[] = _("Thank you!\nI'll send it to your home PC.");
const u8 gText_ThanksIllSendItHome[] = _("Thanks!\nI'll send it to your PC at home.");
const u8 gText_YouDontHaveMoney[] = _("You don't have enough money.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreRoomForThis[] = _("You have no more room for this\nitem.{PAUSE_UNTIL_PRESS}");
const u8 gText_SpaceForVar1Full[] = _("The space for {STR_VAR_1} is full.{PAUSE_UNTIL_PRESS}");
const u8 gText_AnythingElseICanHelp[] = _("Is there anything else I can help\nyou with?");
const u8 gText_CanIHelpWithAnythingElse[] = _("Can I help you with anything else?");
const u8 gText_ThrowInPremierBall[] = _("I'll throw in a Premier Orb, too.{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowInPremierBalls[] = _("I'll throw in {STR_VAR_1} Premier Orbs, too.{PAUSE_UNTIL_PRESS}");
const u8 gText_CantBuyKeyItem[] = _("{STR_VAR_2}? Oh, no.\nI can't buy that.{PAUSE_UNTIL_PRESS}");
const u8 gText_HowManyToSell[] = _("{STR_VAR_2}?\nHow many would you like to sell?");
const u8 gText_ICanPayVar1[] = _("I can pay ¥{STR_VAR_1}.\nWould that be okay?");
const u8 gText_TurnedOverVar1ForVar2[] = _("Turned over the {STR_VAR_2}\nand received ¥{STR_VAR_1}.");
const u8 gText_PokedollarVar1[] = _("¥{STR_VAR_1}");
const u8 gText_HP3[] = _("HP");
const u8 gText_SpAtk3[] = _("SP. ATK");
const u8 gText_SpDef3[] = _("SP. DEF");
const u8 gText_WontHaveEffect[] = _("It won't have any effect.{PAUSE_UNTIL_PRESS}");
const u8 gText_NextFusionMon[] = _("Choose {PKMN} to fuse with.");
const u8 gText_CantBeUsedOnPkmn[] = _("This can't be used on\nthat Bonéka.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCantSwitchOut[] = _("{STR_VAR_1} can't be switched\nout!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyInBattle[] = _("{STR_VAR_1} is already\nin battle!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadySelected[] = _("{STR_VAR_1} has already been\nselected.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHasNoEnergy[] = _("{STR_VAR_1} has no energy\nleft to battle!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantSwitchWithAlly[] = _("You can't switch {STR_VAR_1}'s\nBonéka with one of yours!{PAUSE_UNTIL_PRESS}");
const u8 gText_EggCantBattle[] = _("An EGG can't battle!{PAUSE_UNTIL_PRESS}");
const u8 gText_CantUseUntilNewBadge[] = _("This can't be used until a new\nBadge is obtained.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMoreThanVar1Pkmn[] = _("No more than {STR_VAR_1} Bonéka\nmay enter.{PAUSE_UNTIL_PRESS}");
const u8 gText_SendMailToPC[] = _("Send the removed Mail to\nyour PC?");
const u8 gText_MailSentToPC[] = _("The Mail was sent to your PC.{PAUSE_UNTIL_PRESS}");
const u8 gText_PCMailboxFull[] = _("Your PC's Mailbox is full.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailMessageWillBeLost[] = _("If the MaiL is removed, the\nmessage will be lost. Okay?");
const u8 gText_RemoveMailBeforeItem[] = _("Mail must be removed before\nholding an item.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWasGivenItem[] = _("{STR_VAR_1} was given the\n{STR_VAR_2} to hold.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyHoldingItemSwitch[] = _("{STR_VAR_1} is already holding\none {STR_VAR_2}.\pWould you like to switch the\ntwo items?");
const u8 gText_PkmnNotHolding[] = _("{STR_VAR_1} isn't holding\nanything.{PAUSE_UNTIL_PRESS}");
const u8 gText_ReceivedItemFromPkmn[] = _("Received the {STR_VAR_2}\nfrom {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTakenFromPkmn[] = _("Mail was taken from the\nBonéka.{PAUSE_UNTIL_PRESS}");
const u8 gText_SwitchedPkmnItem[] = _("The {STR_VAR_2} was taken and\nreplaced with the {STR_VAR_1}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHoldingItemCantHoldMail[] = _("This Bonéka is holding an\nitem. It cannot hold Mail.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailTransferredFromMailbox[] = _("Mail was transferred from\nthe Mailbox.{PAUSE_UNTIL_PRESS}");
const u8 gText_BagFullCouldNotRemoveItem[] = _("The Bag is full. The Bonéka's\nitem could not be removed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnLearnedMove3[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!");
const u8 gText_PkmnCantLearnMove[] = _("{STR_VAR_1} and {STR_VAR_2}\nare not compatible.\p{STR_VAR_2} can't be\nlearned.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnNeedsToReplaceMove[] = _("{STR_VAR_1} wants to learn the\nmove {STR_VAR_2}.\pHowever, {STR_VAR_1} already\nknows four moves.\pShould a move be deleted and\nreplaced with {STR_VAR_2}?");
const u8 gText_StopLearningMove2[] = _("Stop trying to teach\n{STR_VAR_2}?");
const u8 gText_MoveNotLearned[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhichMoveToForget[] = _("Which move should be forgotten?{PAUSE_UNTIL_PRESS}");
const u8 gText_12PoofForgotMove[] = _("1, {PAUSE 15}2, and{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\p{STR_VAR_1} forgot how to\nuse {STR_VAR_2}.\pAnd…{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAlreadyKnows[] = _("{STR_VAR_1} already knows\n{STR_VAR_2}.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnHPRestoredByVar2[] = _("{STR_VAR_1}'s HP was restored\nby {STR_VAR_2} point(s).{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfPoison[] = _("{STR_VAR_1} was cured of its\npoisoning.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnCuredOfParalysis[] = _("{STR_VAR_1} was cured of\nparalysis.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnWokeUp2[] = _("{STR_VAR_1} woke up.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnBurnHealed[] = _("{STR_VAR_1}'s burn was healed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFrostbiteHealed[] = _("{STR_VAR_1}'s frostbite was healed.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnThawedOut[] = _("{STR_VAR_1} was thawed out.{PAUSE_UNTIL_PRESS}");
const u8 gText_PPWasRestored[] = _("PP was restored.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnRegainhedHealth[] = _("{STR_VAR_1} regained health.{PAUSE_UNTIL_PRESS}"); // Unused
const u8 gText_PkmnBecameHealthy[] = _("{STR_VAR_1} became healthy.{PAUSE_UNTIL_PRESS}");
const u8 gText_MovesPPIncreased[] = _("{STR_VAR_1}'s PP increased.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnElevatedToLvVar2[] = _("{STR_VAR_1} was elevated to\nLv. {STR_VAR_2}.");
const u8 gText_PkmnGainedExp[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGainedExpAndElevatedToLvVar3[] = _("{STR_VAR_1} gained {STR_VAR_2} Exp. Points\nand was elevated to Lv. {STR_VAR_3}!");
const u8 gText_PkmnBaseVar2StatIncreased[] = _("{STR_VAR_1}'s base {STR_VAR_2}\nstat was raised.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2Fell[] = _("{STR_VAR_1} turned friendly.\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnAdoresBaseVar2Fell[] = _("{STR_VAR_1} adores you!\nThe base {STR_VAR_2} fell!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnFriendlyBaseVar2CantFall[] = _("{STR_VAR_1} turned friendly.\nThe base {STR_VAR_2} can't fall!{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnSnappedOutOfConfusion[] = _("{STR_VAR_1} snapped out of its\nconfusion.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnGotOverInfatuation[] = _("{STR_VAR_1} got over its\ninfatuation.{PAUSE_UNTIL_PRESS}");
const u8 gText_PkmnTransformed[] = _("{STR_VAR_1} transformed!{PAUSE_UNTIL_PRESS}");
const u8 gText_ThrowAwayItem[] = _("Throw away this\n{STR_VAR_1}?");
const u8 gText_ItemThrownAway[] = _("The {STR_VAR_1}\nwas thrown away.{PAUSE_UNTIL_PRESS}");
const u8 gText_TeachWhichPokemon2[] = _("Teach which Bonéka?"); // Unused
const u8 gText_ChoosePokemon[] = _("Choose a Bonéka.");
const u8 gText_MoveToWhere[] = _("Move to where?");
const u8 gText_TeachWhichPokemon[] = _("Teach which Bonéka?");
const u8 gText_UseOnWhichPokemon[] = _("Use on which Bonéka?");
const u8 gText_GiveToWhichPokemon[] = _("Give to which Bonéka?");
const u8 gText_DoWhatWithPokemon[] = _("Do what with this {PKMN}?");
const u8 gText_NothingToCut[] = _("There's nothing to Cut.");
const u8 gText_CantSurfHere[] = _("You can't Surf here.");
const u8 gText_AlreadySurfing[] = _("You're already Surfing.");
const u8 gText_CantUseHere[] = _("Can't use that here.");
const u8 gText_RestoreWhichMove[] = _("Restore which move?");
const u8 gText_BoostPp[] = _("Boost PP of which move?");
const u8 gText_DoWhatWithItem[] = _("Do what with an item?");
const u8 gText_NoPokemonForBattle[] = _("No Bonéka for battle!");
const u8 gText_ChoosePokemon2[] = _("Choose a Bonéka.");
const u8 gText_NotEnoughHp[] = _("Not enough HP…");
const u8 gText_PokemonAreNeeded[] = _("{STR_VAR_1} Bonéka are needed.");
const u8 gText_PokemonCantBeSame[] = _("Bonéka can't be the same.");
const u8 gText_NoIdenticalHoldItems[] = _("No identical hold items.");
const u8 gText_CurrentIsTooFast[] = _("The current is much too fast!");
const u8 gText_DoWhatWithMail[] = _("Do what with the MAIL?");
const u8 gText_ChoosePokemonCancel[] = _("Choose Bonéka or CANCEL.");
const u8 gText_ChoosePokemonConfirm[] = _("Choose Bonéka and confirm.");
const u8 gText_SendWhichMonToPC[] = _("Send which Bonéka to the PC?");
const u8 gText_MoveItemWhere[] = _("Move item to where?");
const u8 gText_XsYAnd[] = _("{STR_VAR_1}'s {STR_VAR_2} and\n");
const u8 gText_XsYWereSwapped[] = _("{STR_VAR_1}'s {STR_VAR_2} were swapped!{PAUSE_UNTIL_PRESS}");
const u8 gText_EnjoyCycling[] = _("Let's enjoy cycling!");
const u8 gText_InUseAlready_PM[] = _("This is in use already.");
const u8 gText_AlreadyHoldingOne[] = _("{STR_VAR_1} is already holding\none {STR_VAR_2}.");
const u8 gText_WhichAppliance[] = _("Order which\nappliance?");
const u8 gText_NoUse[] = _("No use.");
const u8 gText_Able[] = _("Able");
const u8 gText_First_PM[] = _("First");
const u8 gText_Second_PM[] = _("Second");
const u8 gText_Third_PM[] = _("Third");
const u8 gText_Able2[] = _("Able");
const u8 gText_NotAble[] = _("Not able");
const u8 gText_Able3[] = _("Able!");
const u8 gText_NotAble2[] = _("Not able!");
const u8 gText_Learned[] = _("Learned");
const u8 gText_Have[] = _("Have");
const u8 gText_DontHave[] = _("Don't have");
const u8 gText_Fourth[] = _("Fourth");
const u8 gText_PkmnCantParticipate[] = _("That Bonéka can't participate.{PAUSE_UNTIL_PRESS}");
const u8 gText_CancelParticipation[] = _("Cancel participation?");
const u8 gText_CancelBattle[] = _("Cancel the battle?");
const u8 gText_ReturnToWaitingRoom[] = _("Return to the Waiting Room?");
const u8 gText_CancelChallenge[] = _("Cancel the challenge?");
const u8 gText_EscapeFromHere[] = _("Want to escape from here and return\nto {STR_VAR_1}?");
const u8 gText_ReturnToHealingSpot[] = _("Want to return to the healing spot\nused last in {STR_VAR_1}?");
const u8 gText_PauseUntilPress[] = _("{PAUSE_UNTIL_PRESS}");
const u8 gJPText_AreYouSureYouWantToSpinTradeMon[] = _("{STR_VAR_1}を ぐるぐるこうかんに\nだして よろしいですか？");
ALIGNED(4) const u8 gText_OnlyPkmnForBattle[] = _("That's your only\nBonéka for battle.");
ALIGNED(4) const u8 gText_PkmnCantBeTradedNow[] = _("That Bonéka can't be traded\nnow.");
ALIGNED(4) const u8 gText_PkmnCantBeTraded[] = _("That Bonéka can't be traded.");
ALIGNED(4) const u8 gText_EggCantBeTradedNow[] = _("An Egg can't be traded now.");
ALIGNED(4) const u8 gText_OtherTrainersPkmnCantBeTraded[] = _("The other Puppeteer's Bonéka\ncan't be traded now.");
ALIGNED(4) const u8 gText_OtherTrainerCantAcceptPkmn[] = _("The other Puppeteer can't accept\nthat Bonéka now.");
ALIGNED(4) const u8 gText_CantTradeWithTrainer[] = _("You can't trade with that\nPuppeteer now.");
ALIGNED(4) const u8 gText_NotPkmnOtherTrainerWants[] = _("That isn't the type of Bonéka\nthat the other Puppeteer wants.");
ALIGNED(4) const u8 gText_ThatIsntAnEgg[] = _("That isn't an EGG.");
const u8 gText_Register[] = _("Register");
const u8 gText_Attack3[] = _("Attack");
const u8 gText_Defense3[] = _("Defense");
const u8 gText_SpAtk4[] = _("Sp. Atk");
const u8 gText_SpDef4[] = _("Sp. Def");
const u8 gText_Speed2[] = _("Speed");
const u8 gText_HP4[] = _("HP");
const u8 gText_EmptyString8[] = _(""); // Unused
const u8 gText_OTSlash[] = _("OT/");
const u8 gText_RentalPkmn[] = _("Rental Bonéka");
const u8 gText_TypeSlash[] = _("Type/");
const u8 gText_Power[] = _("Power");
const u8 gText_Accuracy2[] = _("Accuracy");
const u8 gText_Appeal[] = _("Appeal");
const u8 gText_Jam[] = _("Jam");
const u8 gText_Status[] = _("Status");
const u8 gText_ExpPoints[] = _("Exp. Points");
const u8 gText_NextLv[] = _("Next Lv.");
const u8 gText_RibbonsVar1[] = _("Ribbons: {STR_VAR_1}");
const u8 gText_EmptyString5[] = _("");
const u8 gText_Events[] = _("Events"); // Unused
const u8 gText_Switch[] = _("Switch");
const u8 gText_PkmnInfo[] = _("Bonéka Info");
const u8 gText_PkmnSkills[] = _("Bonéka Skills");
const u8 gText_BattleMoves[] = _("Battle Moves");
const u8 gText_ContestMoves[] = _("Contest Moves");
const u8 gText_Info[] = _("Info");
const u8 gText_EggWillTakeALongTime[] = _("It looks like this Egg will\ntake a long time to hatch.");
const u8 gText_EggWillTakeSomeTime[] = _("What will hatch from this?\nIt will take some time.");
const u8 gText_EggWillHatchSoon[] = _("It moves occasionally.\nIt should hatch soon.");
const u8 gText_EggAboutToHatch[] = _("It's making sounds.\nIt's about to hatch!");
const u8 gText_HMMovesCantBeForgotten2[] = _("HM moves can't be\nforgotten now.");
const u8 gText_XNatureMetAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nmet at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedAtYZ[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nhatched at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNatureObtainedInTrade[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nobtained in a trade.");
const u8 gText_XNatureFatefulEncounter[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nobtained in a fateful\nencounter at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureProbablyMetAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nprobably met at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1},\n{DYNAMIC 0}{DYNAMIC 4}{DYNAMIC 1}.");
const u8 gText_XNature[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature");
const u8 gText_XNatureMetSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nmet somewhere at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_XNatureHatchedSomewhereAt[] = _("{DYNAMIC 0}{DYNAMIC 2}{DYNAMIC 1}{DYNAMIC 5} nature,\nhatched somewhere at {LV_2}{DYNAMIC 0}{DYNAMIC 3}{DYNAMIC 1}.");
const u8 gText_OddEggFoundByCouple[] = _("An odd Bonéka Egg found\nby the Day Care couple.");
const u8 gText_PeculiarEggNicePlace[] = _("A peculiar Bonéka Egg\nobtained at the nice place.");
const u8 gText_PeculiarEggTrade[] = _("A peculiar Bonéka Egg\nobtained in a trade.");
const u8 gText_EggFromHotSprings[] = _("A Bonéka Egg obtained\nat the hot springs.");
const u8 gText_EggFromTraveler[] = _("An odd Bonéka Egg\nobtained from a traveler.");
const u8 gText_ApostropheSBase[] = _("'s Base");
const u8 gText_OkayToDeleteFromRegistry[] = _("Is it okay to delete {STR_VAR_1}\nfrom the Registry?");
const u8 gText_RegisteredDataDeleted[] = _("The registered data was deleted.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoRegistry[] = _("There is no REGISTRY.{PAUSE_UNTIL_PRESS}");
const u8 gText_DelRegist[] = _("Del Regist.");
const u8 gText_Var3Var1SlashVar2[] = _("{STR_VAR_3}{STR_VAR_1}/{STR_VAR_2}"); // Unused
const u8 gText_Decorate[] = _("Decorate");
const u8 gText_PutAway[] = _("Put Away");
const u8 gText_Toss2[] = _("Toss");
const u8 gText_Color161Shadow161[] = _("{COLOR 161}{SHADOW 161}");
const u8 gText_PutOutSelectedDecorItem[] = _("Put out the selected decoration item.");
const u8 gText_StoreChosenDecorInPC[] = _("Store the chosen decoration in the PC.");
const u8 gText_ThrowAwayUnwantedDecors[] = _("Throw away unwanted decorations.");
const u8 gText_NoDecorations[] = _("There are no decorations.{PAUSE_UNTIL_PRESS}");
const u8 gText_Desk[] = _("Desk");
const u8 gText_Chair[] = _("Chair");
const u8 gText_Plant[] = _("Plant");
const u8 gText_Ornament[] = _("Ornament");
const u8 gText_Mat[] = _("Mat");
const u8 gText_Poster[] = _("Poster");
const u8 gText_Doll[] = _("Doll");
const u8 gText_Cushion[] = _("Cushion");
const u8 gText_Gold[] = _("Gold");
const u8 gText_Silver[] = _("Silver");
const u8 gText_PlaceItHere[] = _("Place it here?");
const u8 gText_CantBePlacedHere[] = _("It can't be placed here.");
const u8 gText_CancelDecorating[] = _("Cancel decorating?");
const u8 gText_InUseAlready[] = _("This is in use already.");
const u8 gText_NoMoreDecorations[] = _("No more decorations can be placed.\nThe most that can be placed are {STR_VAR_1}.");
const u8 gText_NoMoreDecorations2[] = _("No more decorations can be placed.\nThe most that can be placed are {STR_VAR_1}.");
const u8 gText_MustBePlacedOnDesk[] = _("This can't be placed here.\nIt must be on a DESK, etc."); // Unused
const u8 gText_CantPlaceInRoom[] = _("This decoration can't be placed in\nyour own room.");
const u8 gText_CantThrowAwayInUse[] = _("This decoration is in use.\nIt can't be thrown away.");
const u8 gText_DecorationWillBeDiscarded[] = _("This {STR_VAR_1} will be discarded.\nIs that okay?");
const u8 gText_DecorationThrownAway[] = _("The decoration item was thrown away.");
const u8 gText_StopPuttingAwayDecorations[] = _("Stop putting away decorations?");
const u8 gText_NoDecorationHere[] = _("There is no decoration item here.");
const u8 gText_ReturnDecorationToPC[] = _("Return this decoration to the PC?");
const u8 gText_DecorationReturnedToPC[] = _("The decoration was returned to the PC.");
const u8 gText_NoDecorationsInUse[] = _("There are no decorations in use.{PAUSE_UNTIL_PRESS}");
const u8 gText_Tristan[] = _("Tristan");
const u8 gText_Philip[] = _("Philip");
const u8 gText_Dennis[] = _("Dennis");
const u8 gText_Roberto[] = _("Roberto");
const u8 gText_NoItems[] = _("There are no items.{PAUSE_UNTIL_PRESS}");
const u8 gText_NoMailHere[] = _("There's no MAIL here.{PAUSE_UNTIL_PRESS}");
const u8 gText_WhatToDoWithVar1sMail[] = _("What would you like to do with\n{STR_VAR_1}'s Mail?");
const u8 gText_MessageWillBeLost[] = _("The message will be lost.\nIs that okay?");
const u8 gText_BagIsFull[] = _("The Bag is full.{PAUSE_UNTIL_PRESS}");
const u8 gText_MailToBagMessageErased[] = _("The MAIL was returned to the BAG\nwith its message erased.{PAUSE_UNTIL_PRESS}");
const u8 gText_Dad[] = _("Dad");
const u8 gText_Mom[] = _("Mom");
const u8 gText_Wallace[] = _("Wallace");
const u8 gText_Steven[] = _("Steven");
const u8 gText_Brawly[] = _("Brawly");
const u8 gText_Winona[] = _("Winona");
const u8 gText_Phoebe[] = _("Phoebe");
const u8 gText_Glacia[] = _("Glacia");
const u8 gText_Info2[] = _("Info");
const u8 gText_CoolnessContest[] = _("Coolness Contest");
const u8 gText_BeautyContest[] = _("Beauty Contest");
const u8 gText_CutenessContest[] = _("Cuteness Contest");
const u8 gText_SmartnessContest[] = _("Smartness Contest");
const u8 gText_ToughnessContest[] = _("Toughness Contest");
const u8 gText_Decoration2[] = _("Decoration");
const u8 gText_PackUp[] = _("Pack up");
const u8 gText_Registry[] = _("Registry");
const u8 gText_Information[] = _("Information");
const u8 gText_Yes[] = _("Yes");
const u8 gText_No[] = _("No");
const u8 gText_Lv50[] = _("Lv. 50");
const u8 gText_OpenLevel[] = _("Open Level");
const u8 gText_RedShard[] = _("Red Shard");
const u8 gText_YellowShard[] = _("Yellow Shard");
const u8 gText_BlueShard[] = _("Blue Shard");
const u8 gText_GreenShard[] = _("GREEN SHARD");
const u8 gText_BattleFrontier[] = _("Battle Frontier");
const u8 gText_Cool[] = _("Cool");
const u8 gText_Beauty[] = _("Beauty");
const u8 gText_Cute[] = _("Cute");
const u8 gText_Smart[] = _("Smart");
const u8 gText_Tough[] = _("Tough");
const u8 gText_Normal[] = _("Normal");
const u8 gText_Super[] = _("Super");
const u8 gText_Hyper[] = _("Hyper");
const u8 gText_Master[] = _("Master");
const u8 gText_Cool2[] = _("Cool");
const u8 gText_Beauty2[] = _("Beauty");
const u8 gText_Cute2[] = _("Cute");
const u8 gText_Smart2[] = _("Smart");
const u8 gText_Tough2[] = _("Tough");
const u8 gText_Items[] = _("Items");
const u8 gText_Key_Items[] = _("Key Items");
const u8 gText_Poke_Balls[] = _("Sealing Orbs");
const u8 gText_TMs_Hms[] = _("TMs & HMs");
const u8 gText_Berries2[] = _("Berries");
const u8 gText_SomeonesPC[] = _("Someone's PC");
const u8 gText_LanettesPC[] = _("Lanette's PC");
const u8 gText_PlayersPC[] = _("{PLAYER}'s PC");
const u8 gText_HallOfFame[] = _("Hall of Fame");
const u8 gText_LogOff[] = _("Log off");
const u8 gText_Opponent[] = _("Opponent");
const u8 gText_Tourney_Tree[] = _("Tourney Tree");
const u8 gText_ReadyToStart[] = _("Ready to start");
const u8 gText_Single2[] = _("Single");
const u8 gText_Double2[] = _("Double");
const u8 gText_Multi[] = _("Multi");
const u8 gText_MultiLink[] = _("Multi-Link");
const u8 gText_MenuOptionPokedex[] = _("Artbook");
const u8 gText_MenuOptionPokemon[] = _("Bonéka");
const u8 gText_MenuOptionBag[] = _("Bag");
const u8 gText_MenuOptionPokenav[] = _("TohoNav");
const u8 gText_Blank[] = _("");
const u8 gText_MenuOptionSave[] = _("Save");
const u8 gText_MenuOptionOption[] = _("Option");
const u8 gText_MenuOptionExit[] = _("Exit");
const u8 gText_SouthernIsland[] = _("Southern Island");
const u8 gText_BirthIsland[] = _("Birth Island");
const u8 gText_FarawayIsland[] = _("Faraway Island");
const u8 gText_NavelRock[] = _("Navel Rock");
const u8 gText_NormalTagMatch[] = _("Normal Tag Match");
const u8 gText_VarietyTagMatch[] = _("Variety Tag Match");
const u8 gText_UniqueTagMatch[] = _("Unique Tag Match");
const u8 gText_ExpertTagMatch[] = _("Expert Tag Match");
const u8 gText_TradeCenter[] = _("Trade Center");
const u8 gText_Colosseum[] = _("Colosseum");
const u8 gText_RecordCorner[] = _("Record Corner");
const u8 gText_BerryCrush3[] = _("Berry Crush");
const u8 gText_BattleRules[] = _("Battle Rules");
const u8 gText_JudgeMind[] = _("Judge: Mind");
const u8 gText_JudgeSkill[] = _("Judge: Skill");
const u8 gText_JudgeBody[] = _("Judge: Body");
const u8 gText_BasicRules[] = _("Basic Rules");
const u8 gText_SwapPartners[] = _("Swap: Partner");
const u8 gText_SwapNumber[] = _("Swap: Number");
const u8 gText_SwapNotes[] = _("Swap: Notes");
const u8 gText_BattleBasics[] = _("Battle Basics");
const u8 gText_PokemonNature[] = _("Bonéka Nature");
const u8 gText_PokemonMoves[] = _("Bonéka MoveS");
const u8 gText_Underpowered[] = _("Underpowered");
const u8 gText_WhenInDanger[] = _("WHen in danger");
const u8 gText_BattlePokemon[] = _("Battle Bonéka");
const u8 gText_BattleTrainers[] = _("Battle Puppeteers");
const u8 gText_GoOn[] = _("Go on");
const u8 gText_Record2[] = _("Record");
const u8 gText_Rest[] = _("Rest");
const u8 gText_Retire[] = _("Retire");
const u8 gText_1F[] = _("1F");
const u8 gText_2F[] = _("2F");
const u8 gText_3F[] = _("3F");
const u8 gText_4F[] = _("4F");
const u8 gText_5F[] = _("5F");
const u8 gText_6F[] = _("6F");
const u8 gText_7F[] = _("7F");
const u8 gText_8F[] = _("8F");
const u8 gText_9F[] = _("9F");
const u8 gText_10F[] = _("10F");
const u8 gText_11F[] = _("11F");
const u8 gText_B1F[] = _("B1F");
const u8 gText_B2F[] = _("B2F");
const u8 gText_B3F[] = _("B3F");
const u8 gText_B4F[] = _("B4F");
const u8 gText_Rooftop[] = _("Rooftop");
const u8 gText_ElevatorNowOn[] = _("Now on:");
const u8 gText_BP[] = _("BP");
const u8 gText_RankingHall[] = _("Ranking HalL");
const u8 gText_ExchangeService[] = _("Exchange Service");
const u8 gText_LilycoveCity[] = _("Lilycove City");
const u8 gText_SlateportCity[] = _("Slateport City");
const u8 gText_Exit[] = _("Exit");
const u8 gText_YourPartysFull[] = _("Your party's full!{PAUSE_UNTIL_PRESS}");
const u8 gText_NatureSlash[] = _("Nature/");
const u8 gText_InParty[] = _("In party");
const u8 gText_PokemonMaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonFemaleLv[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonNoGenderLv[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}"); // Unused
const u8 gText_PokemonMaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_RED WHITE GREEN}♂{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonFemaleLv2[] = _("{DYNAMIC 0}{COLOR_HIGHLIGHT_SHADOW LIGHT_GREEN WHITE BLUE}♀{COLOR_HIGHLIGHT_SHADOW DARK_GRAY WHITE LIGHT_GRAY}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_PokemonNoGenderLv2[] = _("{DYNAMIC 0}/{LV}{DYNAMIC 1}{DYNAMIC 2}"); // Unused
const u8 gText_CombineFourWordsOrPhrases[] = _("Combine four words or phrases");
const u8 gText_AndMakeYourProfile[] = _("and make your profile.");
const u8 gText_CombineSixWordsOrPhrases[] = _("Combine six words or phrases");
const u8 gText_AndMakeAMessage[] = _("and make a message.");
const u8 gText_FindWordsThatDescribeYour[] = _("Find words that describe your");
const u8 gText_FeelingsRightNow[] = _("feelings right now.");
const u8 gText_WithFourPhrases[] = _("With four phrases,"); // Unused
const u8 gText_CombineNineWordsOrPhrases[] = _("Combine nine words or phrases");
const u8 gText_AndMakeAMessage2[] = _("and make a message.");
const u8 gText_ChangeJustOneWordOrPhrase[] = _("Change just one word or phrase");
const u8 gText_AndImproveTheBardsSong[] = _("and improve the BARD's song.");
const u8 gText_YourProfile[] = _("Your profile");
const u8 gText_YourFeelingAtTheBattlesStart[] = _("Your feeling at the battle's start");
const u8 gText_WhatYouSayIfYouWin[] = _("What you say if you win a battle");
const u8 gText_WhatYouSayIfYouLose[] = _("What you say if you lose a battle");
const u8 gText_TheAnswer[] = _("The answer");
const u8 gText_TheMailMessage[] = _("The Mail message");
const u8 gText_TheMailSalutation[] = _("The Mail salutation"); // Unused
const u8 gText_TheBardsSong2[] = _("The new song");
const u8 gText_CombineTwoWordsOrPhrases[] = _("Combine two words or phrases");
const u8 gText_AndMakeATrendySaying[] = _("and make a trendy saying.");
const u8 gText_TheTrendySaying[] = _("The trendy saying");
const u8 gText_IsAsShownOkay[] = _("is as shown. Okay?");
const u8 gText_CombineTwoWordsOrPhrases2[] = _("Combine two words or phrases");
const u8 gText_ToTeachHerAGoodSaying[] = _("to teach her a good saying.");
const u8 gText_FindWordsWhichFit[] = _("Find words which fit");
const u8 gText_TheTrainersImage[] = _("the Puppeteer's image.");
const u8 gText_TheImage[] = _("The image:");
const u8 gText_OutOfTheListedChoices[] = _("Out of the listed choices,");
const u8 gText_SelectTheAnswerToTheQuiz[] = _("select the answer to the quiz!");
const u8 gText_AndCreateAQuiz[] = _("and create a quiz!");
const u8 gText_PickAWordOrPhraseAnd[] = _("Pick a word or phrase and");
const u8 gText_SetTheQuizAnswer[] = _("set the quiz answer.");
const u8 gText_TheAnswerColon[] = _("The answer:");
const u8 gText_TheQuizColon[] = _("The quiz:"); // Unused
const u8 gText_ApprenticePhrase[] = _("Apprentice's phrase:");
const u8 gText_QuitEditing[] = _("Quit editing?");
const u8 gText_StopGivingPkmnMail[] = _("Stop giving the Bonéka Mail?");
const u8 gText_AndFillOutTheQuestionnaire[] = _("and fill out the questionnaire.");
const u8 gText_LetsReplyToTheInterview[] = _("Let's reply to the interview!");
const u8 gText_AllTextBeingEditedWill[] = _("All the text being edited will");
const u8 gText_BeDeletedThatOkay[] = _("be deleted. Is that okay?");
const u8 gText_QuitEditing2[] = _("Quit editing?"); // Unused
const u8 gText_EditedTextWillNotBeSaved[] = _("The edited text will not be saved."); // Unused
const u8 gText_IsThatOkay[] = _("Is that okay?"); // Unused
const u8 gText_PleaseEnterPhraseOrWord[] = _("Please enter a phrase or word."); // Unused
const u8 gText_EntireTextCantBeDeleted[] = _("The entire text can't be deleted.");
const u8 gText_OnlyOnePhrase[] = _("Only one phrase may be changed.");
const u8 gText_OriginalSongWillBeUsed[] = _("The original song will be used.");
const u8 gText_ThatsTrendyAlready[] = _("That's trendy already!"); // Unused
const u8 gText_CombineTwoWordsOrPhrases3[] = _("Combine two words or phrases.");
const u8 gText_QuitGivingInfo[] = _("Quit giving information?"); // Unused
const u8 gText_StopGivingPkmnMail2[] = _("Stop giving the Bonéka Mail?"); // Unused
const u8 gText_CreateAQuiz2[] = _("Create a quiz!"); // Unused
const u8 gText_SetTheAnswer[] = _("Set the answer!"); // Unused
const u8 gText_CancelSelection[] = _("Cancel the selection?"); // Unused
const u8 gText_Profile[] = _("Profile");
const u8 gText_AtTheBattlesStart[] = _("At the battle's start:");
const u8 gText_UponWinningABattle[] = _("Upon winning a battle:");
const u8 gText_UponLosingABattle[] = _("Upon losing a battle:");
const u8 gText_TheBardsSong[] = _("The Bard's Song");
const u8 gText_WhatsHipAndHappening[] = _("What's hip and happening?");
const u8 gText_Interview[] = _("Interview");
const u8 gText_GoodSaying[] = _("Good saying");
const u8 gText_FansQuestion[] = _("Fan's question");
const u8 gJPText_WhatIsTheQuizAnswer[] = _("クイズの こたえは？"); // Unused
const u8 gText_ApprenticesPhrase[] = _("Apprentice's phrase");
const u8 gText_Questionnaire[] = _("Questionnaire");
const u8 gText_YouCannotQuitHere[] = _("You cannot quit here.");
const u8 gText_SectionMustBeCompleted[] = _("This section must be completed.");
const u8 gText_F700sQuiz[] = _("{DYNAMIC 0}'s quiz");
const u8 gText_Lady[] = _("Lady");
const u8 gText_AfterYouHaveReadTheQuiz[] = _("After you have read the quiz");
const u8 gText_QuestionPressTheAButton[] = _("question, press the A Button.");
const u8 gText_TheQuizAnswerIs[] = _("The quiz answer is?");
const u8 gText_LikeToQuitQuiz[] = _("Would you like to quit this quiz");
const u8 gText_ChallengeQuestionMark[] = _("challenge?");
const u8 gText_IsThisQuizOK[] = _("Is this quiz OK?");
const u8 gText_CreateAQuiz[] = _("Create a quiz!");
const u8 gText_SelectTheAnswer[] = _("Select the answer!");
const u8 gText_LyricsCantBeDeleted[] = _("The lyrics can't be deleted.");
const u8 gText_PokemonLeague[] = _("Bonéka League");
const u8 gText_PokemonCenter[] = _("Bonéka Center");
const u8 gText_GetsAPokeBlockQuestion[] = _(" gets a {POKEBLOCK}?");
const u8 gText_Coolness[] = _("Coolness ");
const u8 gText_Beauty3[] = _("Beauty ");
const u8 gText_Cuteness[] = _("Cuteness ");
const u8 gText_Smartness[] = _("Smartness ");
const u8 gText_Toughness[] = _("Toughness ");
const u8 gText_WasEnhanced[] = _("was enhanced!");
const u8 gText_NothingChanged[] = _("Nothing changed!");
const u8 gText_WontEatAnymore[] = _("It won't eat anymore…");
const u8 gText_SaveFailedCheckingBackup[] = _("Save failed. Checking the backup\nmemory… Please wait.\n{COLOR RED}“Time required: about 1 minute”");
const u8 gText_BackupMemoryDamaged[] = _("The backup memory is damaged, or\nthe internal battery has run dry.\nYou can still play, but not save.");
const u8 gText_GamePlayCannotBeContinued[] = _("{COLOR RED}“Game play cannot be continued.\nReturning to the title screen…”");
const u8 gText_CheckCompleted[] = _("Check completed.\nAttempting to save again.\nPlease wait.");
const u8 gText_SaveCompleteGameCannotContinue[] = _("Save completed.\n{COLOR RED}“Game play cannot be continued.\nReturning to the title screen.”");
const u8 gText_SaveCompletePressA[] = _("Save completed.\n{COLOR RED}“Please press the A Button.”");
const u8 gText_Ferry[] = _("Ferry");
const u8 gText_SecretBase[] = _("Secret Base");
const u8 gText_Hideout[] = _("Hideout");
const u8 gText_ResetRTCConfirmCancel[] = _("Reset RTC?\nA: Confirm, B: Cancel");
const u8 gText_PresentTime[] = _("Present time in game");
const u8 gText_PreviousTime[] = _("Previous time in game");
const u8 gText_PleaseResetTime[] = _("Please reset the time.");
const u8 gText_ClockHasBeenReset[] = _("The clock has been reset.\nData will be saved. Please wait.");
const u8 gText_SaveCompleted[] = _("Save completed.");
const u8 gText_SaveFailed[] = _("Save failed…");
const u8 gText_NoSaveFileCantSetTime[] = _("There is no save file, so the time\ncan't be set.");
const u8 gText_InGameClockUsable[] = _("The in-game clock adjustment system\nis now useable.");
const u8 gText_Slots[] = _("Slots");
const u8 gText_Roulette[] = _("Roulette");
const u8 gText_Good[] = _("Good");
const u8 gText_VeryGood[] = _("Very good");
const u8 gText_Excellent[] = _("Excellent");
const u8 gText_SoSo[] = _("So-so");
const u8 gText_Bad[] = _("Bad");
const u8 gText_TheWorst[] = _("The worst");
const u8 gText_Spicy2[] = _("spicy");
const u8 gText_Dry2[] = _("dry");
const u8 gText_Sweet2[] = _("sweet");
const u8 gText_Bitter2[] = _("bitter");
const u8 gText_Sour2[] = _("sour");
const u8 gText_Single[] = _("SINGLE");
const u8 gText_Double[] = _("DOUBLE");
const u8 gText_Jackpot[] = _("jackpot");
const u8 gText_First[] = _("first");
const u8 gText_Second[] = _("second");
const u8 gText_Third[] = _("third");
#if OW_POISON_DAMAGE < GEN_4
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} fainted…\p\n");
#else
const u8 gText_PkmnFainted_FldPsn[] = _("{STR_VAR_1} survived the poisoning.\nThe poison faded away!\p");
#endif
const u8 gText_Marco[] = _("Marco");
const u8 gText_TrainerCardName[] = _("Name: ");
const u8 gText_TrainerCardIDNo[] = _("IDNo.");
const u8 gText_TrainerCardMoney[] = _("Money");
const u8 gText_PokeDollar[] = _("¥"); // Unused
const u8 gText_TrainerCardPokedex[] = _("Artbook");
const u8 gText_EmptyString6[] = _("");
const u8 gText_Colon2[] = _(":");
const u8 gText_Points[] = _(" points"); // Unused
const u8 gText_TrainerCardTime[] = _("Time");
const u8 gJPText_BattlePoints[] = _("ゲ-ムポイント"); // Unused. Name presumed, translation is Game Points
const u8 gText_Var1sTrainerCard[] = _("{STR_VAR_1}'s Puppeteer's Card");
const u8 gText_HallOfFameDebut[] = _("Hall of Fame Debut  ");
const u8 gText_LinkBattles[] = _("Link Battles");
const u8 gText_LinkCableBattles[] = _("LINK CABLE BATTLES");
const u8 gText_WinsLosses[] = _("W:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  L:{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_PokemonTrades[] = _("Bonéka Trades");
const u8 gText_UnionTradesAndBattles[] = _("Union Trades & Battles");
const u8 gText_BerryCrush[] = _("Berry Crush");
const u8 gText_WaitingTrainerFinishReading[] = _("Waiting for the other Puppeteer to\nfinish reading your Puppeteer Card.");
const u8 gText_PokeblocksWithFriends[] = _("{POKEBLOCK}S w/Friends");
const u8 gText_NumPokeblocks[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}");
const u8 gText_WonContestsWFriends[] = _("WON CONTESTS W/FRIENDS");
const u8 gText_BattlePtsWon[] = _("Battle Points won");
const u8 gText_NumBP[] = _("{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BP");
const u8 gText_BattleTower[] = _("Battle Tower");
const u8 gText_WinsStraight[] = _("W/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_1}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}  STRAIGHT/{COLOR RED}{SHADOW LIGHT_RED}{STR_VAR_2}");
const u8 gText_BattleTower2[] = _("Battle Tower");
const u8 gText_BattleDome[] = _("Battle Dome");
const u8 gText_BattlePalace[] = _("Battle Palace");
const u8 gText_BattleFactory[] = _("Battle Factory");
const u8 gText_BattleArena[] = _("Battle Arena");
const u8 gText_BattlePike[] = _("Battle Pike");
const u8 gText_BattlePyramid[] = _("Battle Pyramid");

ALIGNED(4) const u8 gText_FacilitySingle[] = _("{STR_VAR_1} Single");
ALIGNED(4) const u8 gText_FacilityDouble[] = _("{STR_VAR_1} Double");
ALIGNED(4) const u8 gText_FacilityMulti[] = _("{STR_VAR_1} Multi");
ALIGNED(4) const u8 gText_FacilityLink[] = _("{STR_VAR_1} Link");
ALIGNED(4) const u8 gText_Facility[] = _("{STR_VAR_1}");

const u8 gText_Give[] = _("Give");
const u8 gText_NoNeed[] = _("No need");
const u8 gText_ColorLightShadowDarkGray[] = _("{COLOR LIGHT_GRAY}{SHADOW DARK_GRAY}");
const u8 gText_ColorBlue[] = _("{COLOR BLUE}");
const u8 gText_ColorTransparent[] = _("{HIGHLIGHT TRANSPARENT}{COLOR TRANSPARENT}");
const u8 gText_CDot[] = _("C.");
const u8 gText_BDot[] = _("B.");
const u8 gText_AnnouncingResults[] = _("Announcing the results!");
const u8 gText_PreliminaryResults[] = _("The preliminary results!");
const u8 gText_Round2Results[] = _("Round 2 results!");
const u8 gText_ContestantsMonWon[] = _("{STR_VAR_1}'s {STR_VAR_2} won!");
const u8 gText_CommunicationStandby[] = _("Communication standby…");
const u8 gText_ColorDarkGray[] = _("{COLOR DARK_GRAY}");
const u8 gText_ColorDynamic6WhiteDynamic5[] = _("{COLOR_HIGHLIGHT_SHADOW DYNAMIC_COLOR6 WHITE DYNAMIC_COLOR5}"); // Unused
const u8 gText_HealthboxNickname[] = _("{HIGHLIGHT DARK_GRAY}");
const u8 gText_EmptySpace2[] = _(" "); // Unused
const u8 gText_HealthboxGender_Male[] = _("{COLOR DYNAMIC_COLOR2}♂");
const u8 gText_HealthboxGender_Female[] = _("{COLOR DYNAMIC_COLOR1}♀");
const u8 gText_HealthboxGender_None[] = _("{COLOR DYNAMIC_COLOR2}");
const u8 gText_Upper[] = _("UPPER");
const u8 gText_Lower[] = _("lower");
const u8 gText_Others[] = _("Others");
const u8 gText_Symbols[] = _("Symbols");
const u8 gText_Register2[] = _("Register");
const u8 gText_Exit2[] = _("Exit");
const u8 gText_QuitChatting[] = _("Quit chatting?");
const u8 gText_RegisterTextWhere[] = _("Register text where?");
const u8 gText_RegisterTextHere[] = _("Register text here?");
const u8 gText_InputText[] = _("Input text.");
const u8 gText_F700JoinedChat[] = _("{DYNAMIC 0} joined the chat!");
const u8 gText_F700LeftChat[] = _("{DYNAMIC 0} left the chat.");
const u8 gJPText_PlayersXPokemon[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめ:"); // Unused
const u8 gJPText_PlayersXPokmonDoesNotExist[] = _("{DYNAMIC 0}の{DYNAMIC 1}ひきめは いません"); // Unused
const u8 gText_ExitingChat[] = _("Exiting the chat…");
const u8 gText_LeaderLeftEndingChat[] = _("The LEADER, {DYNAMIC 0}, has\nleft, ending the chat.");
const u8 gText_RegisteredTextChangedOKToSave[] = _("The registered text has been changed.\nIs it okay to save the game?");
const u8 gText_AlreadySavedFile_Chat[] = _("There is already a saved file.\nIs it okay to overwrite it?");
const u8 gText_SavingDontTurnOff_Chat[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u8 gText_PlayerSavedGame_Chat[] = _("{DYNAMIC 0} saved the game.");
const u8 gText_IfLeaderLeavesChatEnds[] = _("If the LEADER leaves, the chat\nwill end. Is that okay?");
const u8 gText_Hello[] = _("Hello");
const u8 gText_Pokemon2[] = _("Bonéka");
const u8 gText_Trade[] = _("Trade");
const u8 gText_Battle[] = _("Battle");
const u8 gText_Lets[] = _("Let's");
const u8 gText_Ok[] = _("OK!");
const u8 gText_Sorry[] = _("Sorry");
const u8 gText_YaySmileEmoji[] = _("Yay{EMOJI_BIGSMILE}");
const u8 gText_ThankYou[] = _("Thank you");
const u8 gText_ByeBye[] = _("Bye-bye!");
const u8 gText_PlayerScurriedToCenter[] = _("{PLAYER} scurried to a Bonéka Center,\nprotecting the exhausted and fainted\nBonéka from further harm…\p");
const u8 gText_PlayerScurriedBackHome[] = _("{PLAYER} scurried back home, protecting\nthe exhausted and fainted Bonéka from\nfurther harm…\p");
const u8 gText_PlayerRegroupCenter[] = _("{PLAYER} went running back to a Bonéka Center\nto regroup and reconsider their battle\lstrategy…\p");
const u8 gText_PlayerRegroupHome[] = _("{PLAYER} went running back home to regroup\nand reconsider their battle strategy…\p");
const u8 gText_HatchedFromEgg[] = _("{STR_VAR_1} hatched from the Egg!");
const u8 gText_NicknameHatchPrompt[] = _("Would you like to nickname the newly\nhatched {STR_VAR_1}?");
ALIGNED(4) const u8 gText_ReadyPickBerry[] = _("Are you ready to Berry-Crush?\nPlease pick a Berry for use.\p");
ALIGNED(4) const u8 gText_WaitForAllChooseBerry[] = _("Please wait while each member\nchooses a Berry.");
ALIGNED(4) const u8 gText_EndedWithXUnitsPowder[] = _("{PAUSE_MUSIC}{PLAY_BGM MUS_LEVEL_UP}You ended up with {STR_VAR_1} units of\nsilky-smooth Berry Powder.{RESUME_MUSIC}\pYour total amount of Berry Powder\nis {STR_VAR_2}.\p");
ALIGNED(4) const u8 gText_RecordingGameResults[] = _("Recording your game results in the\nsave file.\lPlease wait.");
ALIGNED(4) const u8 gText_PlayBerryCrushAgain[] = _("Want to play Berry Crush again?");
ALIGNED(4) const u8 gText_YouHaveNoBerries[] = _("You have no BERRIES.\nThe game will be canceled.");
ALIGNED(4) const u8 gText_MemberDroppedOut[] = _("A member dropped out.\nThe game will be canceled.");
ALIGNED(4) const u8 gText_TimesUpNoGoodPowder[] = _("Time's up.\pGood Berry Powder could not be\nmade…\p");
ALIGNED(4) const u8 gText_CommunicationStandby2[] = _("Communication standby…");
ALIGNED(4) const u8 gText_1DotBlueF700[] = _("1. {COLOR BLUE}{SHADOW LIGHT_BLUE}{DYNAMIC 0}");
ALIGNED(4) const u8 gText_1DotF700[] = _("1. {DYNAMIC 0}");
ALIGNED(4) const u8 gText_SpaceTimes2[] = _(" time(s)");
ALIGNED(4) const u8 gText_XDotY[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_Var1Berry[] = _("{STR_VAR_1} BERRY");
ALIGNED(4) const u8 gText_TimeColon[] = _("Time:");
ALIGNED(4) const u8 gText_PressingSpeed[] = _("Pressing Speed:");
ALIGNED(4) const u8 gText_Silkiness[] = _("Silkiness:");
ALIGNED(4) const u8 gText_StrVar1[] = _("{STR_VAR_1}");
ALIGNED(4) const u8 gText_SpaceMin[] = _(" min. ");
ALIGNED(4) const u8 gText_XDotY2[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_SpaceSec[] = _(" sec.");
ALIGNED(4) const u8 gText_XDotY3[] = _("{STR_VAR_1}.{STR_VAR_2}");
ALIGNED(4) const u8 gText_TimesPerSec[] = _(" Times/sec.");
ALIGNED(4) const u8 gText_Var1Percent[] = _("{STR_VAR_1}%");
ALIGNED(4) const u8 gText_PressesRankings[] = _("No. of Presses Rankings");
ALIGNED(4) const u8 gText_CrushingResults[] = _("Crushing Results");
ALIGNED(4) const u8 gText_NeatnessRankings[] = _("Neatness Rankings");
ALIGNED(4) const u8 gText_CoopRankings[] = _("Cooperative Rankings");
ALIGNED(4) const u8 gText_PressingPowerRankings[] = _("Pressing-Power Rankings");
const u8 gText_BerryCrush2[] = _("Berry Crush");
const u8 gText_PressingSpeedRankings[] = _("Pressing-Speed Rankings");
const u8 gText_Var1Players[] = _("{STR_VAR_1} Players");
const u8 gText_SymbolsEarned[] = _("Symbols Earned");
const u8 gText_BattleRecord[] = _("Battle Record");
const u8 gText_BattlePoints[] = _("Battle Points");
const u8 gText_UnusedCancel[] = _("Cancel"); // Unused
const u8 gText_EmptyString7[] = _("");
const u8 gText_CheckFrontierMap[] = _("Check Battle Frontier Map.");
const u8 gText_CheckTrainerCard[] = _("Check Puppeteer Card.");
const u8 gText_ViewRecordedBattle[] = _("View recorded battle.");
const u8 gText_PutAwayFrontierPass[] = _("Put away the Frontier Pass.");
const u8 gText_CurrentBattlePoints[] = _("Your current Battle Points.");
const u8 gText_CollectedSymbols[] = _("Your collected Symbols.");
const u8 gText_BattleTowerAbilitySymbol[] = _("Battle Tower - Ability Symbol");
const u8 gText_BattleDomeTacticsSymbol[] = _("Battle Dome - Tactics Symbol");
const u8 gText_BattlePalaceSpiritsSymbol[] = _("Battle Palace - Spirits Symbol");
const u8 gText_BattleArenaGutsSymbol[] = _("Battle Arena - Guts Symbol");
const u8 gText_BattleFactoryKnowledgeSymbol[] = _("Battle Factory - Knowledge Symbol");
const u8 gText_BattlePikeLuckSymbol[] = _("Battle Pike - Luck Symbol");
const u8 gText_BattlePyramidBraveSymbol[] = _("Battle Pyramid - Brave Symbol");
const u8 gText_ThereIsNoBattleRecord[] = _("There is no Battle Record.");
const u8 gText_BattleTower3[] = _("Battle Tower");
const u8 gText_BattleDome2[] = _("Battle Dome");
const u8 gText_BattlePalace2[] = _("Battle Palace");
const u8 gText_BattleArena2[] = _("Battle Arena");
const u8 gText_BattleFactory2[] = _("Battle Factory");
const u8 gText_BattlePike2[] = _("Battle Pike");
const u8 gText_BattlePyramid2[] = _("Battle Pyramid");
const u8 gText_BattleTowerDesc[] = _("KO opponents and aim for the top!\nYour ability will be tested.");
const u8 gText_BattleDomeDesc[] = _("Keep winning at the tournament!\nYour tactics will be tested.");
const u8 gText_BattlePalaceDesc[] = _("Watch your Bonéka battle!\nYour spirit will be tested.");
const u8 gText_BattleArenaDesc[] = _("Win battles with teamed-up Bonéka!\nYour guts will be tested.");
const u8 gText_BattleFactoryDesc[] = _("Aim for victory using rental Bonéka!\nYour knowledge will be tested.");
const u8 gText_BattlePikeDesc[] = _("Select one of three paths to battle!\nYour luck will be tested.");
const u8 gText_BattlePyramidDesc[] = _("Aim for the top with exploration!\nYour bravery will be tested.");
const u8 gText_Powder[] = _("Powder");
const u8 gText_BerryPickingRecords[] = _("Dodrio Berry-picking Records");
const u8 gText_BerriesPicked[] = _("Berries picked:");
const u8 gText_BestScore[] = _("Best score:");
const u8 gText_BerriesInRowFivePlayers[] = _("BERRIES picked in a row with\nfive players:");
const u8 gText_BerryPickingResults[] = _("Announcing BERRY-PICKING results!");
const u8 gText_10P30P50P50P[] = _("{CLEAR_TO 0x03}10P{CLEAR_TO 0x2B}30P{CLEAR_TO 0x53}50P{CLEAR_TO 0x77}{EMOJI_MINUS}50P");
const u8 gText_AnnouncingRankings[] = _("Announcing rankings!");
const u8 gText_AnnouncingPrizes[] = _("Announcing prizes!");
const u8 gText_1Colon[] = _("1:");
const u8 gText_2Colon[] = _("2:");
const u8 gText_3Colon[] = _("3:");
const u8 gText_4Colon[] = _("4:");
const u8 gText_5Colon[] = _("5:");
const u8 gText_FirstPlacePrize[] = _("The first-place winner gets\nthis {DYNAMIC 0}!");
const u8 gText_CantHoldAnyMore[] = _("You can't hold any more!");
const u8 gText_FilledStorageSpace[] = _("It filled its storage space.");
const u8 gText_WantToPlayAgain[] = _("Want to play again?");
const u8 gText_SomeoneDroppedOut[] = _("Somebody dropped out.\nThe link will be canceled.");
const u8 gText_SpacePoints[] = _(" points");
const u8 gText_CommunicationStandby3[] = _("Communication standby…");
const u8 gText_SpacePoints2[] = _(" points");
const u8 gText_SpaceTimes3[] = _(" time(s)");
const u8 gText_PkmnJumpRecords[] = _("Bonéka Jump Records");
const u8 gText_JumpsInARow[] = _("Jumps in a row:");
const u8 gText_BestScore2[] = _("Best score:");
const u8 gText_ExcellentsInARow[] = _("Excellents in a row:");
const u8 gText_AwesomeWonF701F700[] = _("Awesome score! You've\nwon {DYNAMIC 1} {DYNAMIC 0}!");
const u8 gText_FilledStorageSpace2[] = _("It filled its storage space.");
const u8 gText_CantHoldMore[] = _("You can't hold any more!");
const u8 gText_WantToPlayAgain2[] = _("Want to play again?");
const u8 gText_SomeoneDroppedOut2[] = _("Somebody dropped out.\nThe link will be canceled.");
const u8 gText_CommunicationStandby4[] = _("Communication standby…");
const u8 gText_LinkContestResults[] = _("{PLAYER}'s Link Contest Results");
const u8 gText_1st[] = _("1st");
const u8 gText_2nd[] = _("2nd");
const u8 gText_3rd[] = _("3rd");
const u8 gText_4th[] = _("4th");
const u8 gText_Friend[] = _("Friend");
const u8 gText_Pokemon3[] = _("Bonéka"); // Unused
const u8 gJPText_MysteryGift[] = _("ふしぎなもらいもの");
const u8 gJPText_DecideStop[] = _("{A_BUTTON}けってい {B_BUTTON}やめる");
const u8 gJPText_ReceiveMysteryGiftWithEReader[] = _("カードeリーダー{PLUS}　で\nふしぎなもらいものを　よみこみます");
const u8 gJPText_SelectConnectFromEReaderMenu[] = _("カードeリーダー{PLUS}の　メニューから\n‘つうしん'を　えらび");
const u8 gJPText_SelectConnectWithGBA[] = _("‘ゲームボーイアドバンスとつうしん'\nを　せんたく　してください");
const u8 gJPText_SelectConnectAndPressA[] = _("カードeリーダー{PLUS}の　‘つうしん'を\nえらんで　Aボタンを　おしてください"); // Unused
const u8 gJPText_LinkIsIncorrect[] = _("せつぞくが　まちがっています");
const u8 gJPText_CardReadingHasBeenHalted[] = _("カードの　よみこみを\nちゅうし　しました");
const u8 gJPText_UnableConnectWithEReader[] = _("カードeリーダー{PLUS}と\nつうしん　できません"); // Unused
const u8 gJPText_Connecting[] = _("つうしん　ちゅう　です");
const u8 gJPText_ConnectionErrorCheckLink[] = _("つうしん　エラーです\nせつぞくを　たしかめて　ください");
const u8 gJPText_ConnectionErrorTryAgain[] = _("つうしん　エラーです\nはじめから　やりなおして　ください"); // Link error
const u8 gJPText_AllowEReaderToLoadCard[] = _("カードeリーダー{PLUS}　に\nカードを　よみこませて　ください");
const u8 gJPText_ConnectionComplete[] = _("つうしん　しゅうりょう！");
const u8 gJPText_NewTrainerHasComeToHoenn[] = _("あらたな　トレーナーが\nホウエンに　やってきた！");
const u8 gJPText_PleaseWaitAMoment[] = _("しばらく　おまちください");
const u8 gJPText_WriteErrorUnableToSaveData[] = _("かきこみ　エラー　です\nデータが　ほぞん　できませんでした");
const u8 gText_SingleBattleRoomResults[] = _("{PLAYER}'s Single Battle Room Results");
const u8 gText_DoubleBattleRoomResults[] = _("{PLAYER}'s Double Battle Room Results");
const u8 gText_MultiBattleRoomResults[] = _("{PLAYER}'s Multi Battle Room Results");
const u8 gText_LinkMultiBattleRoomResults[] = _("{PLAYER}'s Link Multi Battle Room Results");
const u8 gText_SingleBattleTourneyResults[] = _("{PLAYER}'s Single Battle Tourney Results");
const u8 gText_DoubleBattleTourneyResults[] = _("{PLAYER}'s Double Battle Tourney Results");
const u8 gText_SingleBattleHallResults[] = _("{PLAYER}'s Single Battle Hall Results");
const u8 gText_DoubleBattleHallResults[] = _("{PLAYER}'s Double Battle Hall Results");
const u8 gText_BattleChoiceResults[] = _("{PLAYER}'s Battle Choice Results");
const u8 gText_SetKOTourneyResults[] = _("{PLAYER}'s Set KO Tourney Results");
const u8 gText_BattleSwapSingleResults[] = _("{PLAYER}'s Battle Swap Single Results");
const u8 gText_BattleSwapDoubleResults[] = _("{PLAYER}'s Battle Swap Double Results");
const u8 gText_BattleQuestResults[] = _("{PLAYER}'s Battle Quest Results");
const u8 gText_Lv502[] = _("Lv. 50");
const u8 gText_OpenLv[] = _("Open Lv.");
const u8 gText_WinStreak[] = _("Win streak: {STR_VAR_1}");
const u8 gText_Current[] = _("Current");
const u8 gText_Record[] = _("Record");
const u8 gText_Prev[] = _("Prev.");
const u8 gText_RentalSwap[] = _("Rental/Swap");
const u8 gText_Total[] = _("Total");
const u8 gText_ClearStreak[] = _("Clear streak: {STR_VAR_1}");
const u8 gText_Championships[] = _("Championships: {STR_VAR_1}");
const u8 gText_RoomsCleared[] = _("Rooms cleared: {STR_VAR_1}");
const u8 gText_TimesCleared[] = _("Times cleared:{CLEAR 0x05}{STR_VAR_1}");
const u8 gText_KOsInARow[] = _("KOs in a row: {STR_VAR_1}");
const u8 gText_TimesVar1[] = _("Times: {STR_VAR_1}");
const u8 gText_FloorsCleared[] = _("Floors cleared: {STR_VAR_1}");

ALIGNED(4) const u8 gText_RecordsLv50[] = _("LV. 50");
ALIGNED(4) const u8 gText_RecordsOpenLevel[] = _("OPEN LEVEL");
ALIGNED(4) const u8 gText_FrontierFacilityWinStreak[] = _("Win streak: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityClearStreak[] = _("Clear streak: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityRoomsCleared[] = _("Rooms cleared: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityKOsStreak[] = _("KOs in a row: {STR_VAR_2}");
ALIGNED(4) const u8 gText_FrontierFacilityFloorsCleared[] = _("Floors cleared: {STR_VAR_2}");
ALIGNED(4) const u8 gText_123Dot[][3] = {_("1."), _("2."), _("3.")};

const u8 gText_SavingDontTurnOff2[] = _("SAVING…\nDON'T TURN OFF THE POWER.");
const u8 gText_BlenderMaxSpeedRecord[] = _("Berry Blender\nMaximum Speed Record!");
const u8 gText_234Players[] = _("2 Players\n3 Players\n4 Players");
const u8 gText_YesNo[] = _("Yes\nNo");
const u8 gText_SelectorArrow3[] = _("▶");
const u8 gText_Peekaboo[] = _("Peekaboo!");
const u8 gText_CommErrorCheckConnections[] = _("Communication error…\nPlease check all connections,\nthen turn the power off and on.");
const u8 gText_CommErrorEllipsis[] = _("Communication error…");
const u8 gText_MoveCloserToLinkPartner[] = _("Move closer to your link partner(s).\nAvoid obstacles between partners.");
const u8 gText_ABtnRegistrationCounter[] = _("A Button: Registration Counter");
const u8 gText_ABtnTitleScreen[] = _("A Button: Title Screen");
const u8 gText_Option[] = _("Option");
const u8 gText_TextSpeed[] = _("Text Speed");
const u8 gText_BattleScene[] = _("Battle Scene");
const u8 gText_BattleStyle[] = _("Battle Style");
const u8 gText_Sound[] = _("Sound");
const u8 gText_Frame[] = _("Frame");
const u8 gText_OptionMenuCancel[] = _("Cancel");
const u8 gText_ButtonMode[] = _("Button mode");
const u8 gText_TextSpeedSlow[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Slow");
const u8 gText_TextSpeedMid[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Mid");
const u8 gText_TextSpeedFast[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Fast");
const u8 gText_BattleSceneOn[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}On");
const u8 gText_BattleSceneOff[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Off");
const u8 gText_BattleStyleShift[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Shift");
const u8 gText_BattleStyleSet[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Set");
const u8 gText_SoundMono[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Mono");
const u8 gText_SoundStereo[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Stereo");
const u8 gText_FrameType[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Type");
const u8 gText_FrameTypeNumber[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}");
const u8 gText_ButtonTypeNormal[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}Normal");
const u8 gText_ButtonTypeLR[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}LR");
const u8 gText_ButtonTypeLEqualsA[] = _("{COLOR GREEN}{SHADOW LIGHT_GREEN}L=A");
const u8 gText_NumPlayerLink[] = _("{STR_VAR_1}p Link");
const u8 gText_BronzeCard[] = _("Bronze");
const u8 gText_CopperCard[] = _("Copper");
const u8 gText_SilverCard[] = _("Silver");
const u8 gText_GoldCard[] = _("Gold");
const u8 gText_Day[] = _("Day");
const u8 gText_Colon3[] = _(":");
const u8 gText_Confirm2[] = _("Confirm");
const u8 gText_Days[] = _("Days"); // Unused
const u8 gText_TimeColon2[] = _("Time:"); // Unused
const u8 gText_GameTime[] = _("Game time"); // Unused
const u8 gText_RTCTime[] = _("RTC time"); // Unused
const u8 gText_UpdatedTime[] = _("Updated time"); // Unused
const u8 gText_MenuPokedex[] = _("Artbook");
const u8 gText_MenuPokemon[] = _("Bonéka");
const u8 gText_MenuBag[] = _("Bag");
const u8 gText_MenuPokenav[] = _("TohoNav");
const u8 gText_MenuPlayer[] = _("{PLAYER}");
const u8 gText_MenuSave[] = _("Save");
const u8 gText_MenuOption[] = _("Option");
const u8 gText_MenuExit[] = _("Exit");
const u8 gText_MenuRetire[] = _("Retire");
const u8 gText_MenuRest[] = _("Rest");
const u8 gText_MenuDexNav[] = _("TohoNav");
const u8 gText_SafariBallStock[] = _("Safari Orbs\nStock: {STR_VAR_1}");
const u8 gText_BattlePyramidFloor[] = _("Battle Pyramid\n{STR_VAR_1}");
const u8 gText_Floor1[] = _("Floor 1");
const u8 gText_Floor2[] = _("Floor 2");
const u8 gText_Floor3[] = _("Floor 3");
const u8 gText_Floor4[] = _("Floor 4");
const u8 gText_Floor5[] = _("Floor 5");
const u8 gText_Floor6[] = _("Floor 6");
const u8 gText_Floor7[] = _("Floor 7");
const u8 gText_Peak[] = _("Peak");
const u8 gText_LinkStandby2[] = _("Link standby…\n… … B Button: Cancel");
const u8 gText_PressAToLoadEvent[] = _("Press the A Button to load event.\n… … B Button: Cancel");
const u8 gText_LoadingEvent[] = _("Loading event…");
const u8 gText_DontRemoveCableTurnOff[] = _("Don't remove the Game Link cable.\nDon't turn off the power.");
const u8 gText_EventSafelyLoaded[] = _("The event was safely loaded.");
const u8 gText_LoadErrorEndingSession[] = _("Loading error.\nEnding session.");
const u8 gJPText_Player[] = _("プレイヤー"); // Unused
const u8 gJPText_Sama[] = _("さま"); // Unused
const u8 gText_DexHoenn[] = _("Hoenn");
const u8 gText_DexNational[] = _("National");
const u8 gText_PokedexDiploma[] = _("Player: {CLEAR 0x10}{COLOR RED}{SHADOW LIGHT_RED}{PLAYER}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}\n\nThis document certifies\nthat you have successfully\ncompleted your\n{STR_VAR_1} Artbook.\n\n{CLEAR_TO 0x42}{COLOR RED}{SHADOW LIGHT_RED}GAME FREAK");
const u8 gJPText_GameFreak[] = _("{COLOR RED}{SHADOW LIGHT_RED}ゲ-ムフリ-ク"); // Unused
const u8 gText_DiplomaEmpty[] = _("{COLOR RED}{SHADOW LIGHT_RED}"); // Unused
const u8 gText_Kanto[] = _("Kanto");
const u8 gText_Johto[] = _("Johto");
const u8 gText_Hoenn[] = _("Hoenn");
const u8 gText_OhABite[] = _("Oh! A bite!");
const u8 gText_PokemonOnHook[] = _("A Bonéka's on the hook!{PAUSE_UNTIL_PRESS}");
const u8 gText_NotEvenANibble[] = _("Not even a nibble…{PAUSE_UNTIL_PRESS}");
const u8 gText_ItGotAway[] = _("It got away…{PAUSE_UNTIL_PRESS}");
const u8 gText_XWillBeSentToY[] = _("{STR_VAR_2} will be\nsent to {STR_VAR_1}.");
const u8 gText_ByeByeVar1[] = _("Bye-bye, {STR_VAR_2}!");
const u8 gText_XSentOverY[] = _("{STR_VAR_1} sent over {STR_VAR_3}.");
const u8 gText_TakeGoodCareOfX[] = _("Take good care of {STR_VAR_3}!");

// Easy chat group names
const u8 gEasyChatGroupName_Pokemon[] = _("Bonéka");
const u8 gEasyChatGroupName_Trainer[] = _("Puppeteer");
const u8 gEasyChatGroupName_Status[] = _("Status");
const u8 gEasyChatGroupName_Battle[] = _("Battle");
const u8 gEasyChatGroupName_Greetings[] = _("Greetings");
const u8 gEasyChatGroupName_People[] = _("People");
const u8 gEasyChatGroupName_Voices[] = _("Voices");
const u8 gEasyChatGroupName_Speech[] = _("Speech");
const u8 gEasyChatGroupName_Endings[] = _("Endings");
const u8 gEasyChatGroupName_Feelings[] = _("Feelings");
const u8 gEasyChatGroupName_Conditions[] = _("Conditions");
const u8 gEasyChatGroupName_Actions[] = _("Actions");
const u8 gEasyChatGroupName_Lifestyle[] = _("Lifestyle");
const u8 gEasyChatGroupName_Hobbies[] = _("Hobbies");
const u8 gEasyChatGroupName_Time[] = _("Time");
const u8 gEasyChatGroupName_Misc[] = _("Misc.");
const u8 gEasyChatGroupName_Adjectives[] = _("Adjectives");
const u8 gEasyChatGroupName_Events[] = _("Events");
const u8 gEasyChatGroupName_Move1[] = _("Move 1");
const u8 gEasyChatGroupName_Move2[] = _("Move 2");
const u8 gEasyChatGroupName_TrendySaying[] = _("Trendy saying");
const u8 gEasyChatGroupName_Pokemon2[] = _("Bonéka2");

const u8 gText_ThreeQuestionMarks[] = _("???");
const u8 gText_MaxHP[] = _("Max. HP");
const u8 gText_Attack[] = _("Attack");
const u8 gText_Defense[] = _("Defense");
const u8 gText_Speed[] = _("Speed");
const u8 gText_SpAtk[] = _("Sp. Atk");
const u8 gText_SpDef[] = _("Sp. Def");
const u8 gText_Plus[] = _("{PLUS}");
const u8 gText_Dash[] = _("-");
const u8 gText_FromSpace[] = _("From ");
const u8 gText_MixingRecords[] = _("Mixing records…");
const u8 gText_RecordMixingComplete[] = _("Record mixing completed.\nThank you for waiting.");
const u8 gText_YourName[] = _("Your name?");
const u8 gText_BoxName[] = _("Box name?");
const u8 gText_PkmnsNickname[] = _("{STR_VAR_1}'s nickname?");
const u8 gText_TellHimTheWords[] = _("Tell him the words.");
const u8 gText_MoveOkBack[] = _("{DPAD_NONE}Move  {A_BUTTON}OK  {B_BUTTON}Back");
const u8 gText_RentalPkmn2[] = _("Rental Bonéka");
const u8 gText_SelectFirstPkmn[] = _("Select the first Bonéka.");
const u8 gText_SelectSecondPkmn[] = _("Select the second Bonéka.");
const u8 gText_SelectThirdPkmn[] = _("Select the third Bonéka.");
const u8 gText_Rent[] = _("Rent");
const u8 gText_Summary[] = _("Summary");
const u8 gText_Others2[] = _("Others");
const u8 gText_Deselect[] = _("Deselect");
const u8 gText_TheseThreePkmnOkay[] = _("Are these three Bonéka OK?");
const u8 gText_Yes2[] = _("Yes");
const u8 gText_No2[] = _("No");
const u8 gText_CantSelectSamePkmn[] = _("Can't select same {PKMN}.");
const u8 gText_PkmnSwap[] = _("Bonéka Swap");
const u8 gText_SelectPkmnToSwap[] = _("Select Bonéka to swap.");
const u8 gText_SelectPkmnToAccept[] = _("Select Bonéka to accept.");
const u8 gText_Swap[] = _("Swap");
const u8 gText_Summary2[] = _("Summary");
const u8 gText_Rechoose[] = _("Rechoose");
const u8 gText_QuitSwapping[] = _("Quit swapping?");
const u8 gText_Yes3[] = _("Yes");
const u8 gText_No3[] = _("No");
const u8 gText_PkmnForSwap[] = _("{PKMN} for swap");
const u8 gText_Cancel3[] = _("Cancel");
const u8 gText_Swap2[] = _("Swap"); // Unused
const u8 gText_Accept[] = _("Accept"); // Unused
const u8 gText_AcceptThisPkmn[] = _("Accept this Bonéka?");
const u8 gText_4Spaces[] = _("    "); // Unused
const u8 gText_SamePkmnInPartyAlready[] = _("Same {PKMN} in party already.");
const u8 gText_DecimalPoint[] = _(".");
const u8 gText_SavingPlayer[] = _("Player");
const u8 gText_SavingBadges[] = _("Badges");
const u8 gText_SavingPokedex[] = _("Artbook");
const u8 gText_SavingTime[] = _("Time");
const u8 gText_WirelessCommStatus[] = _("Wireless Communication Status");
const u8 gText_PeopleTrading[] = _("People trading:");
const u8 gText_PeopleBattling[] = _("People battling:");
const u8 gText_PeopleInUnionRoom[] = _("People in the Union Room:");
const u8 gText_PeopleCommunicating[] = _("People communicating:");
const u8 gText_F700Players[] = _("{DYNAMIC 0} players");
const u8 gText_F701Players[] = _("{DYNAMIC 1} players");
const u8 gText_F702Players[] = _("{DYNAMIC 2} players");
const u8 gText_F703Players[] = _("{DYNAMIC 3} players");

const u8 *const gTextTable_Players[] = {
    gText_F700Players,
    gText_F701Players,
    gText_F702Players,
    gText_F703Players
};

ALIGNED(4) const u8 gText_WonderCards[] = _("Wonder Cards");
ALIGNED(4) const u8 gText_WonderNews[] = _("Wonder News");
ALIGNED(4) const u8 gText_WirelessCommunication[] = _("Wireless Communication");
ALIGNED(4) const u8 gText_Friend2[] = _("Friend");
ALIGNED(4) const u8 gText_Exit3[] = _("Exit");
ALIGNED(4) const u8 gText_Receive[] = _("Receive");
ALIGNED(4) const u8 gText_Send[] = _("Send");
ALIGNED(4) const u8 gText_Toss[] = _("Toss");
ALIGNED(4) const u8 gText_VarietyOfEventsImportedWireless[] = _("A variety of events will be imported\nover Wireless Communication.");
ALIGNED(4) const u8 gText_WonderCardsInPossession[] = _("Read the Wonder Cards in your\npossession.");
ALIGNED(4) const u8 gText_ReadNewsThatArrived[] = _("Read the News that arrived.");
ALIGNED(4) const u8 gText_ReturnToTitle[] = _("Return to the title screen.");
ALIGNED(4) const u8 gText_DontHaveCardNewOneInput[] = _("You don't have a Wonder Card,\nso a new Card will be input.");
ALIGNED(4) const u8 gText_DontHaveNewsNewOneInput[] = _("You don't have any Wonder News,\nso new News will be input.");
ALIGNED(4) const u8 gText_WhereShouldCardBeAccessed[] = _("Where should the Wonder Card\nbe accessed?");
ALIGNED(4) const u8 gText_WhereShouldNewsBeAccessed[] = _("Where should the Wonder News\nbe accessed?");
ALIGNED(4) const u8 gText_CommunicationStandbyBButtonCancel[] = _("Communication standby…\nB Button: Cancel"); // Unused
ALIGNED(4) const u8 gText_Communicating[] = _("Communicating…");
ALIGNED(4) const u8 gText_CommunicationCompleted[] = _("Communication completed.");
ALIGNED(4) const u8 gText_CommunicationError[] = _("Communication error.");
ALIGNED(4) const u8 gText_CommunicationCanceled[] = _("Communication has been canceled.");
ALIGNED(4) const u8 gText_ThrowAwayWonderCard[] = _("Throw away the WONDER CARD\nand input a new Card?");
ALIGNED(4) const u8 gText_HaventReceivedCardsGift[] = _("You haven't received the Card's gift\nyet. Input a new Card anyway?");
ALIGNED(4) const u8 gText_WonderCardReceivedFrom[] = _("A Wonder Card has been received\nfrom {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsReceivedFrom[] = _("A Wonder News item has been\nreceived from {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderCardReceived[] = _("A new Wonder Card has been\nreceived.");
ALIGNED(4) const u8 gText_WonderNewsReceived[] = _("A new Wonder News item has been\nreceived.");
ALIGNED(4) const u8 gText_NewStampReceived[] = _("A new Stamp has been received.");
ALIGNED(4) const u8 gText_NewTrainerReceived[] = _("A new Puppeteer has arrived.");
ALIGNED(4) const u8 gText_AlreadyHadCard[] = _("You already had that\nWonder Card.");
ALIGNED(4) const u8 gText_AlreadyHadNews[] = _("You already had that\nWonder News item.");
ALIGNED(4) const u8 gText_AlreadyHadStamp[] = _("You already had that\nStamp.");
ALIGNED(4) const u8 gText_NoMoreRoomForStamps[] = _("There's no more room for adding\nStamps.");
ALIGNED(4) const u8 gText_RecordUploadedViaWireless[] = _("Your record has been uploaded via\nWireless Communication.");
ALIGNED(4) const u8 gText_CantAcceptCardFromTrainer[] = _("You can't accept a Wonder Card\nfrom this Puppeteer.");
ALIGNED(4) const u8 gText_CantAcceptNewsFromTrainer[] = _("You can't accept Wonder News\nfrom this Puppeteer.");
ALIGNED(4) const u8 gText_NothingSentOver[] = _("Nothing was sent over…");
ALIGNED(4) const u8 gText_WhatToDoWithCards[] = _("What would you like to do\nwith the Wonder Cards?");
ALIGNED(4) const u8 gText_WhatToDoWithNews[] = _("What would you like to do\nwith the Wonder News?");
ALIGNED(4) const u8 gText_SendingWonderCard[] = _("Sending your Wonder Card…");
ALIGNED(4) const u8 gText_SendingWonderNews[] = _("Sending your Wonder News item…");
ALIGNED(4) const u8 gText_WonderCardSentTo[] = _("Your Wonder Card has been sent\nto {STR_VAR_1}.");
ALIGNED(4) const u8 gText_WonderNewsSentTo[] = _("Your Wonder News item has been\nsent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_StampSentTo[] = _("A Stamp has been sent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_GiftSentTo[] = _("A Gift has been sent to {STR_VAR_1}.");
ALIGNED(4) const u8 gText_OtherTrainerHasCard[] = _("The other Puppeteer has the same\nWonder Card already.");
ALIGNED(4) const u8 gText_OtherTrainerHasNews[] = _("The other Puppeteer has the same\nWonder News already.");
ALIGNED(4) const u8 gText_OtherTrainerHasStamp[] = _("The other Puppeteer has the same\nStamp already.");
ALIGNED(4) const u8 gText_OtherTrainerCanceled[] = _("The other Puppeteer canceled\ncommunication.");
ALIGNED(4) const u8 gText_CantSendGiftToTrainer[] = _("You can't send a Mystery Gift to\nthis Puppeteer.");
ALIGNED(4) const u8 gText_IfThrowAwayCardEventWontHappen[] = _("If you throw away the Card,\nits event won't happen. Okay?");
ALIGNED(4) const u8 gText_OkayToDiscardNews[] = _("Is it okay to discard this\nNews item?");
ALIGNED(4) const u8 gText_HaventReceivedGiftOkayToDiscard[] = _("You haven't received the\nGift. Is it okay to discard?");
ALIGNED(4) const u8 gText_DataWillBeSaved[] = _("Data will be saved.\nPlease wait.");
ALIGNED(4) const u8 gText_SaveCompletedPressA[] = _("Save completed.\nPlease press the A Button.");
ALIGNED(4) const u8 gText_WonderCardThrownAway[] = _("The Wonder Card was thrown away.");
ALIGNED(4) const u8 gText_WonderNewsThrownAway[] = _("The Wonder News was thrown away.");
ALIGNED(4) const u8 gText_MysteryGift[] = _("Mystery Gift");
ALIGNED(4) const u8 gText_PickOKExit[] = _("{DPAD_UPDOWN}Pick {A_BUTTON}OK {B_BUTTON}Exit");
ALIGNED(4) const u8 gText_PickOKCancel[] = _("{DPAD_UPDOWN}Pick {A_BUTTON}OK {B_BUTTON}Cancel");
const u8 gText_PlayersBattleResults[] = _("{PLAYER}'s Battle Results");
const u8 gText_TotalRecordWLD[] = _("Total Record W:{STR_VAR_1} L:{STR_VAR_2} D:{STR_VAR_3}");
const u8 gText_WinLoseDraw[] = _("{CLEAR_TO 0x53}Win{CLEAR_TO 0x80}Lose{CLEAR_TO 0xB0}DRAW");
const u8 gText_CommunicationStandby5[] = _("Communication standby…");
const u8 gText_QuitTheGame[] = _("Quit the game?");
const u8 gText_YouveGot9999Coins[] = _("You've got 9,999 Coins.");
const u8 gText_YouveRunOutOfCoins[] = _("You've run out of Coins.\nGame over!");
const u8 gText_YouDontHaveThreeCoins[] = _("You don't have three Coins.");
const u8 gText_ReelTimeHelp[] = _("REEL TIME\nHere's your chance to take\naim and nail marks!\nReel Time continues for the\nawarded number of spins.\nIt all ends on a Big Bonus.");
const u8 gDaycareText_GetAlongVeryWell[] = _("The two seem to get along\nvery well.");
const u8 gDaycareText_GetAlong[] = _("The two seem to get along.");
const u8 gDaycareText_DontLikeOther[] = _("The two don't seem to like\neach other much.");
const u8 gDaycareText_PlayOther[] = _("The two prefer to play with other\nBonéka than each other.");
const u8 gText_NewLine2[] = _("\n");
const u8 gText_Exit4[] = _("Exit");
const u8 gText_Lv[] = _("{LV}");
const u8 gText_TimeBoard[] = _("Time Board");
const u8 gText_TimeCleared[] = _("Time Cleared ");
const u8 gText_XMinYDotZSec[] = _("{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sec.");
const u8 gText_TrainerHill1F[] = _("1F");
const u8 gText_TrainerHill2F[] = _("2F");
const u8 gText_TrainerHill3F[] = _("3F");
const u8 gText_TrainerHill4F[] = _("4F");
const u8 gText_TeachWhichMoveToPkmn[] = _("Teach which move to\n{STR_VAR_1}?");
const u8 gText_MoveRelearnerTeachMoveConfirm[] = _("Teach {STR_VAR_2}?");
const u8 gText_MoveRelearnerPkmnLearnedMove[] = _("{STR_VAR_1} learned\n{STR_VAR_2}!");
const u8 gText_MoveRelearnerPkmnTryingToLearnMove[] = _("{STR_VAR_1} is trying to learn\n{STR_VAR_2}.\pBut {STR_VAR_1} can't learn more\nthan four moves.\pDelete an older move to make\nroom for {STR_VAR_2}?");
const u8 gText_MoveRelearnerStopTryingToTeachMove[] = _("Stop trying to teach\n{STR_VAR_2}?");
const u8 gText_MoveRelearnerAndPoof[] = _("{PAUSE 32}1, {PAUSE 15}2, and {PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}Poof!\p");
const u8 gText_MoveRelearnerPkmnForgotMoveAndLearnedNew[] = _("{STR_VAR_1} forgot {STR_VAR_3}.\pAnd…\p{STR_VAR_1} learned {STR_VAR_2}.");
const u8 gText_MoveRelearnedPkmnDidNotLearnMove[] = _("{STR_VAR_1} did not learn the\nmove {STR_VAR_2}."); // Unused
const u8 gText_MoveRelearnerGiveUp[] = _("Give up trying to teach a new\nmove to {STR_VAR_1}?");
const u8 gText_MoveRelearnerWhichMoveToForget[] = _("Which move should be\nforgotten?\p");
const u8 gText_MoveRelearnerBattleMoves[] = _("Battle Moves");
const u8 gText_MoveRelearnerContestMovesTitle[] = _("Contest Moves");
const u8 gText_MoveRelearnerType[] = _("Type/"); // Unused
const u8 gText_MoveRelearnerPP[] = _("PP/");
const u8 gText_MoveRelearnerPower[] = _("Power/");
const u8 gText_MoveRelearnerAccuracy[] = _("Accuracy/");
const u8 gText_MoveRelearnerAppeal[] = _("Appeal");
const u8 gText_MoveRelearnerJam[] = _("Jam");
const u8 gText_Kira[] = _("Kira");
const u8 gText_Amy[] = _("Amy");
const u8 gText_John[] = _("John");
const u8 gText_Roy[] = _("Roy");
const u8 gText_Gabby[] = _("Gabby");
const u8 gText_Anna[] = _("Anna");
const u8 gText_ClearAllSaveData[] = _("Clear all save data areas?");
const u8 gText_ClearingData[] = _("Clearing data…\nPlease wait.");
const u8 gText_IsThisTheCorrectTime[] = _("Is this the correct time?");
const u8 gText_Confirm3[] = _("Confirm");
const u8 gText_Cancel4[] = _("Cancel");
const u8 gText_CommStandbyAwaitingOtherPlayer[] = _("Communication standby…\nAwaiting another player to choose.");
const u8 gText_BattleWasRefused[] = _("The battle was refused.{PAUSE 60}");
const u8 gText_RefusedBattle[] = _("Refused the battle.{PAUSE 60}");
const u8 gText_NoWeather[] = _("No Weather"); // Below are unused debug names for weather types
const u8 gText_Sunny[] = _("Sunny"); // Unused
const u8 gText_Sunny2[] = _("Sunny2"); // Unused
const u8 gText_Rain[] = _("Rain"); // Unused
const u8 gText_Snow[] = _("Snow"); // Unused
const u8 gText_Lightning[] = _("Lightning"); // Unused
const u8 gText_Fog[] = _("Fog"); // Unused
const u8 gText_VolcanoAsh[] = _("Volcano Ash"); // Unused
const u8 gText_Sandstorm[] = _("Sandstorm"); // Unused
const u8 gText_Fog2[] = _("Fog2"); // Unused
const u8 gText_Seafloor[] = _("Seafloor"); // Unused
const u8 gText_Cloudy[] = _("Cloudy"); // Unused
const u8 gText_Sunny3[] = _("Sunny3"); // Unused
const u8 gText_HeavyRain[] = _("Heavy Rain"); // Unused
const u8 gText_Seafloor2[] = _("Seafloor2"); // Unused
const u8 gText_DelAll[] = _("Del. All");
const u8 gText_Cancel5[] = _("Cancel");
const u8 gText_Ok2[] = _("OK");
const u8 gText_Quiz[] = _("Quiz");
const u8 gText_Answer[] = _("Answer");
const u8 gText_PokeBalls[] = _("Sealing Orbs");
const u8 gText_Berry[] = _("Berry");
const u8 gText_Berries[] = _("Berries");
const u8 gText_ExpShareOn[] = _("The Exp. Share has been turned on.{PAUSE_UNTIL_PRESS}");
const u8 gText_ExpShareOff[] = _("The Exp. Share has been turned off.{PAUSE_UNTIL_PRESS}");
const u8 gText_BasePointsResetToZero[] = _("{STR_VAR_1}'s base points\nwere all reset to zero!{PAUSE_UNTIL_PRESS}");
const u8 gText_AM[] = _("AM");
const u8 gText_PM[] = _("PM");
const u8 gText_Relearn[] = _("{START_BUTTON} Relearn"); // future note: don't decap this, because it mimics the summary screen BG graphics which will not get decapped
const u8 gText_Rename[] = _("RENAME");
const u8 gText_CannotSendMonToBoxHM[] = _("Cannot send that mon to the box,\nbecause it knows a HM move.{PAUSE_UNTIL_PRESS}");
